### ISSUE TITLE
Button to "Bake" Controllers, Bones and Structures apperance

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#153]
# Environement

### Tool & Version
- Duik 16

# What's the issue?

- Feature Request

Button to "Bake" Controllers, Bones and Structures apperance, to improve performance once the rig is finished: Removes all expressions and effects concerning the appearance (color, size...) of the (selected) controllers, or bones, or structures, replacing them by the current post-expression value.
The button can be added in the "edit" panels of duik for those objects.

**Comment by WasibQureshi** [comment]
Hi Nicolas, Just baking controllers to key frames or everything should be baked & expressions unlinked?

**Comment by Nico-Duduf** [comment]
I mean, just set the value of all propertiea concerning the apoearance of those layers (their sizes, color, etc.), then remove the expressions, and the correspondong pseuso effect.

This should improve the performance of heavy rigs, and it's friendlier for the animator who has one less unnecessary effect on the layer

El 30 de marzo de 2018 0:05:12 CEST, Wasib Qureshi <notifications@github.com> escribió:
>Hi Nicolas, Just baking controllers to key frames or everything should
>be baked & expressions unlinked?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Rainbox-dev/DuAEF_Duik/issues/153#issuecomment-377386777

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
