### ISSUE TITLE
Wrong tool tips in two sections of DUIK16

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#178]
# Bug Report

# Environement
### Tool & Version
- Duik 16.0.1-Alpha-6

### After Effects
- CC2018 (15.1.0)
- English

### OS
- Mac OS 10.13.4

# What's the issue?
There are wrong tool tips in the following sections:
- Tools > Rename > Project Items
- Links and Constraints > Structures

![add_ik_tooltip](https://user-images.githubusercontent.com/38455050/38854935-5e3d81ee-4222-11e8-94bc-e02fe6e5886c.png)
![rename_tool tip](https://user-images.githubusercontent.com/38455050/38854936-5e5b7eb0-4222-11e8-803d-e44d51010d16.png)

All the best, René

**Comment by Nico-Duduf** [comment]
fixed, thanks!
