### ISSUE TITLE
Can't import composition with rigged character into my project with other rigged characters

### ISSUE THREAD

**Issue by armax9** [Rainbox-dev/DuAEF_Duik#195]
### Steps to reproduce

1.  I have AE project with some rigged characters (with Duik 16).
2. I try to import other rigged (with Duik 16) character from other project. 
3. I get many errors, and my imported composition  is empty. I have nothing in it - no controllers, no layers (legs, arms, body, etc.). And keep getting Error message, when try to open imported composition.

That happens with all my projects with Duik 16 rig.

### Tool & Version
- Duik 16.0.1-Alpha-9 (I also tried older builds)
- CC2018 (15.1.1) (I also tried CC 2017)
- English
- Windows 10
- Bug Report

### Error Message 1
After Effects warning: effect control conversion required in effect "". Some effect cotrols will be reset. To avoid silently resetting these same effect controls on all subsequently loaded projects, save this project and then quit & re-launch After Effects.

(25 :: 0)
### Error Message 2
After Effects error: attempt to get a value from a time stream with no key values.

(29 :: 36)

### Error Message 3
After Effects error: missing data in file.

(33 :: 4)

### Error Message 4
After Effects warning: your project file is apparently damaged (skipped sections: 1). Please save using a different name. 

(26 :: 1)

**Comment by Nico-Duduf** [comment]
Hi,
Thanks for your feedback. This is a bug which happens when using rigs made with different alpha versions of Duik in the same project.
I need to implement a version management for the effects used by Duik to fix this, which will be done soon when we go to Beta versions, when all the new features will be implemented.
