### ISSUE TITLE
DUIK launch error after editing controller colors

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#206]
# Bug Report

# Environement

### Tool & Version
- Duik 16.0.1-Alpha-9

### After Effects
- CC2018 (15.1.1 Build 12)
- English

### OS
- Mac OS 10.13.4

# What's the issue?
After changing the color of controllers it is not possible to use the back button (separate issue actually) to get to the controllers menu. So I closed the DUIK panel. After reopening it, AE shows an error and the panel stays empty

### Error Message
![error](https://user-images.githubusercontent.com/38455050/40575269-49c93c1a-60e2-11e8-8c91-e42450b7ed93.png)

### Error Location
- Line: 5173

### Steps to reproduce
1. recolour controllers 
2. Try to use the »Back« button 
3. Close DUIK panel
4. Invoke DUIK panel

### Expected behaviour
DUIK panel should be activated

### Actual behaviour
After Effects error (see above)

**Comment by Nico-Duduf** [comment]
might be related to #205

**Comment by Nico-Duduf** [comment]
fixed
