### ISSUE TITLE
Characters displaying wrong in contextual help

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#216]
# Bug Report

# Environement

### Tool & Version
- Duik 16.0.1-Alpha-10

### After Effects
- CC2018 (15.1.1)
- English

### OS
- Mac OS 10.13.4

# What's the issue?
The contextual help shows wrong characters with apostrophes and bulleted lists

![characters_missing](https://user-images.githubusercontent.com/38455050/40959637-92d0d810-689d-11e8-9acd-b68f37046348.png)

**Comment by Nico-Duduf** [comment]
Mac... :'( 

Will be fixed soon ;)

**Comment by reneandritsch** [comment]
Nicholas, why does this happen on a Mac?

**Comment by Nico-Duduf** [comment]
I think it has to do with character encoding. I suspect my code editor to use an encoding which is not supported on Mac, I'll check this.

Character encoding is always a pain. And this is only English yet, without accents...
