### ISSUE TITLE
Change of Position Constraint default

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#220]
# Feature Request
Hi Nicholas, when using the position constraint it might happen that one object is moved out of the composition due to the default setting of 100%. This could be confusing for users, if the object suddenly disappears. Maybe you could set it to a lower percentage so that the user sees something happens. I could also live with a default value of 0%. 

### Tool
- Duik

![constraint_default](https://user-images.githubusercontent.com/38455050/40981005-2da23456-68da-11e8-9701-6cb3c9ef164d.gif)

**Comment by Nico-Duduf** [comment]
This has been a problem since I developped the tool, but I never thought about setting the default to 0% ^^

Thanks ;)
