### ISSUE TITLE
Help Panel not closing

### ISSUE THREAD

**Issue by madnespro** [Rainbox-dev/DuAEF_Duik#224]
# Bug Report

When you hit the help button the first time close aparently good (contextual box icon and panel "close" button), the second time you hit the help you can't close it from the contextual box icon, the close button works some times.

# Environement
### Tool & Version
- Duik bassel

### After Effects
- CC2018 (15.0)
- English

### OS

- Windows 10

# What's the issue?
When you hit the help button the first time close aparently good (window/panel close icon (classic X) and panel "close" button), the second time you hit the help you can't close it from the window/panel close icon (classic X), the close button inside the panel works some times.

### Error Location

- File:
- Line:

### Steps to reproduce
1. Open After Effects
2. Clic the button help
3. Close de help panel.
4. Clic the button help
5. Try to close from the 

### Expected behaviour
Close in any case.
### Actual behaviour
Not closing the panel.

**Comment by Nico-Duduf** [comment]
This is a bug in After Effects, unfortunately I can't do anything about this, and this is the reason why I've added a close button at the bottom, which should work.
