### ISSUE TITLE
Very long start up time with DUIK in active workspace (Release Candidate)

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#237]
# Bug Report

# Environement
- Duik 16.0.0-RC1

### After Effects
- CC2018 (15.1.1)
- English

### OS
- Mac OS 10.13.5

# What's the issue?
Starting AE with DUIK (Release Candidate incorporated in the active workspace takes a long time. I don’t know if this is because of the open Help Panel or the script launch.

While taking the video capture (attached) it took AE more than 2 minutes to start up and without video caturing it took AE more than 1 minute to react again.

### Steps to reproduce
< Start AE with DUIK as part of the active workspace
1. 
2. 
3. 

### Expected behaviour
< Regular Startup

### Actual behaviour
<Very long startup and AE not responding for some time

[startup.mov.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/2145657/startup.mov.zip)

**Comment by Nico-Duduf** [comment]
Thanks again for your feedback!

This version of Duik is awfully long to start BUT with the help of Lars Jandell (http://www.larsjandel.de/) we've found a way to make it ten times faster ;)
It will be available saturday or sunday!

Lang lebe Deutschland!

**Comment by reneandritsch** [comment]
Thanks a lot!
