### ISSUE TITLE
no active panel on very first launch = quite empty UI

### ISSUE THREAD

**Issue by LarsJandel** [Rainbox-dev/DuAEF_Duik#242]
# Environement

### Tool & Version
- Duik 16.0.0-RC-2

### After Effects

- CC2018 (15.1.1)
- English

### OS

- Mac OS 10.12.16

# What's the issue?

- start up behaviour: Woohoo - loads fast! :) One tiny detail: You might want Duik to have the first tab active on the very first launch, otherwise it starts quite empty, like in the screenshot. It behaves normal on the next launch.
<img width="386" alt="duik-16 0 0-rc-2-veryfirststartui" src="https://user-images.githubusercontent.com/32457827/42135312-9d4d1a9a-7d49-11e8-9bf7-1985612c22c9.png">

### Error Location

- File:
- Line:

### Steps to reproduce

1. clean AE preferences = no DUIK prefs
2. start Duik for the very first time
3. 

### Expected behaviour

- first tab being active, corresponding UI/icons being displayed

### Actual behaviour

- no tab is active, UI is quite empty

**Comment by reneandritsch** [comment]
Hi Lars, yes true! Thanks for your enhancement to the startup. Nicholas said you are the one with the speed improvements.

**Comment by Nico-Duduf** [comment]
and I've just fixed this one too ;)

**Comment by Nico-Duduf** [comment]
I've made the rigging/Structures panel as the default one, let me know if you feel it should be another one!

**Comment by LarsJandel** [comment]
Nice - rigging/structure is perfect - thanks!
...btw, are you still working on the alignment of elements as most are centered, but some are aligned left..? ;) And the top menu is aligned right atm.
And if you get bored, the language dropdown width will keep it's wide size when the ui is made smaller afterwards - but: cosmetics - usually a user just changes this once and in one session...

**Comment by Nico-Duduf** [comment]
Yes, there are still some cosmetic stuff to adjust, but the priority right now is finishing the doc and the website, and fixing remaining bugs if any ;)
That being said, I'm creating an issue with this for 16.1!
