### ISSUE TITLE
add bones on layer named body fails

### ISSUE THREAD

**Issue by Kemet001** [Rainbox-dev/DuAEF_Duik#245]
# Bug Report

### Tool & Version
- Duik 16.0.0 RC

### After Effects
- CC2018 (15.0)
- English

### OS
- Windows 10

# What's the issue?
When layer is named "body", add bones function fails to create bones corectly - all bones are located in centre of comp.

### Error Message
no message

### Error Location

- File:
- Line:

### Steps to reproduce
1. precomp body layer, name it body
2. place Body composition into bigger composition
3. create pupet tool pins on body precomp inside bigger comp
4. press add bones button

### Expected behaviour
create bones on correct position, based on pins location

### Actual behaviour
all bones are located in centre of comp, mesh is deformed

**Comment by Nico-Duduf** [comment]
Hi, thanks for your feedback.

I can't reproduce this bug here, can you send me your project file please?
Or make a video recording.

Thanks!

**Comment by Kemet001** [comment]
Hi Nicolas

thanks for response - i tried to recreate it in new project and its works.
I am builduing complex character animation, so probably i have some precomp
causing error in my project.
Thanks

ut 3. 7. 2018 o 21:04 Nicolas Dufresne <notifications@github.com>
napísal(a):

> Hi, thanks for your feedback.
>
> I can't reproduce this bug here, can you send me your project file please?
> Or make a video recording.
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/7a24610007df36c29e3454cc3e1c008078ba65a8?url=https%3A%2F%2Fgithub.com%2FRainbox-dev%2FDuAEF_Duik%2Fissues%2F245%23issuecomment-402261780&userId=2299762&signature=d0ca64c5f9ef74fe>,
> or mute the thread
> <https://mailtrack.io/trace/link/60b844ff1f3caeb1ee2ccc5d470a6ac69f2410ea?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAm5sRhdWeo7pre3MDUjdSrsC0wd4lcj3ks5uC8AwgaJpZM4VAnMp&userId=2299762&signature=a2fb49f236d45edf>
> .
>


-- 
*Ing. Peter Kmeť - motion graphic*
*+421 918 072 559*
*petokemet@gmail.com <petokemet@gmail.com>*
*www.peterkmet.com*
<https://mailtrack.io/trace/link/3d2b309deeb3782b1a4ced186b91f6b2e5caebb0?url=http%3A%2F%2Fwww.peterkmet.com&userId=2299762&signature=5deddf3a6ad333ac>

**Comment by Kemet001** [comment]
I fugured out what was problem - you can not have exactly same names of layers in composition. 
when you have layer named "body" and want to add bones, in comp can not be another layer called "body"

**Comment by Nico-Duduf** [comment]
Yes, using expressions in After Effects, you have to make sure all layers have an individual name
