### ISSUE TITLE
Can't install Bissel on my Mac Pro

### ISSUE THREAD

**Issue by seanekimber** [Rainbox-dev/DuAEF_Duik#254]
# Bug Report

# Environement

### Tool & Version
- Duik 16.0.1-Alpha-5

### After Effects
- CC2018 (15.0)
- English

### OS

- Mac OS 10.11.6 (Needs to be this due to our server restrictions)

# What's the issue?
I keep trying to install the Bassel script on my Mac but get an “Unable to execute script at line 6318. undefined is not an object” error when I try to run it. I’ve installed the files into my Script UI Panels folder on CC2018.

### Error Message
Unable to execute script at line 6318. undefined is not an object.

### Error Location

- File:
- Line: 6318

### Steps to reproduce

1. Installing both the script file and the ffmpeg file into the Scripts UI Panel folder in my Adobe CC2018 hierarchy
2.  Trying to run it on After Effects
3. 

### Expected behaviour
I expect it to work. :)

### Actual behaviour
It gives me the error message and then just a blank panel

**Comment by Nico-Duduf** [comment]
Hi,
thanks for your feedback!

There was a small mistake in this version, which broke Duik when it was first installed on the system.

This has been fixed in the upcoming public release (next monday)
