### ISSUE TITLE
color picker error hex code

### ISSUE THREAD

**Issue by msongz** [Rainbox-dev/DuAEF_Duik#256]
# Environement

### Tool & Version

- Duik 16

### After Effects

- CC2018 (15.0)
- English

### OS

- Mac OS 10.13.4

# What's the issue?

- Bug Report

when click 
![image](https://user-images.githubusercontent.com/2059694/42430699-5d6a271c-8373-11e8-9edb-a5a5de392dd1.png)
and select
![image](https://user-images.githubusercontent.com/2059694/42430724-7f0cb86c-8373-11e8-8f94-77c84113b418.png)
then close
![image](https://user-images.githubusercontent.com/2059694/42430727-88ea16b8-8373-11e8-9d4d-6000b19d61d0.png)

**Comment by Nico-Duduf** [comment]
Thanks for your feedback!

This issue is weird... I plan to change the color picker anyway, it should fix this.

#203

**Comment by Nico-Duduf** [comment]
fixed
