### ISSUE TITLE
Suggestions for the UI. Suggestions for the animation blender feature 

### ISSUE THREAD

**Issue by Tim1022** [Rainbox-dev/DuAEF_Duik#260]
# Feature Request

### Tool

- Duik

### Steps

1. may have better names for some buttons.
2. confusing about the two buttons both called animation blender but in the different panel.

### Expected behaviour
More clear function setup which is friendly for the new users.
![snipaste_2018-07-12_12-20-35 jpgg](https://user-images.githubusercontent.com/19354752/42609611-7c7efd6a-85e1-11e8-9b08-e13a698f83d9.jpg)
![snipaste_2018-07-12_12-24-38 jpgg](https://user-images.githubusercontent.com/19354752/42609617-8378c092-85e1-11e8-8db4-a78f020cf097.jpg)
![untitled-1](https://user-images.githubusercontent.com/19354752/42609653-b5610c7c-85e1-11e8-9ead-117fc60b8a9c.jpg)

### Actual behaviour
use the feature in a wrong way and lead to a crash of AE.

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, I'm splitting this into specific issues:
#262

I won't change the "Axis" to "Controller Axis" which would take to much place in the UI.

We're thinking about the animation blender, but how Duik is designed is for teams where the animator and the rigger are not necessarily the same person. It makes sense to separate the tool in a rigging step and an animation step; we want animators to be able to stay most of the time on the animation tab, without any need to get back to the rigging tap (and the opposite for riggers)
