### ISSUE TITLE
autostrech turns off with continuos rasterize beeing on 

### ISSUE THREAD

**Issue by Kemet001** [Rainbox-dev/DuAEF_Duik#261]
# Environement

### Tool & Version
- Duik 16.0.1-Alpha-5

### After Effects

- CC2018 (15.0)
- English

### OS

- Windows 10

# What's the issue?

- Bug Report

### Steps to reproduce

1.  use strech function in pupet tool rig, stretch character to see effect work
2.  in precompose of animated character turn on "continuos rasterize" function
3.  autostrech turns off with continuos  rasterize beeing on 

### Expected behaviour
autostretch should not be affected by continous rasterize function

### Actual behaviour
autostrech turns off with continuos rasterize beeing on

**Comment by Kemet001** [comment]
here is video of this lag: [https://www.dropbox.com/s/85awdjkzahgf0vg/2018-07-12_16-54-24.mp4?dl=0](url)

**Comment by Nico-Duduf** [comment]
Hi, thanks for your feedback.

This has nothing to do with Duik, it's just how After Effects work, and how coordinates change when continuous rasterization is activated.
