### ISSUE TITLE
Blender Keyframes

### ISSUE THREAD

**Issue by zakria257** [Rainbox-dev/DuAEF_Duik#265]
Hi!
How to add keyframes to fluid simulation in blender so that it can be imported to Unity to work smoothly?

**Comment by Nico-Duduf** [comment]
I don't really understand what you mean,
Can you post more details, examples or screenshots please?

**Comment by zakria257** [comment]
Actually the problem is i've made a fluid animation in blender as well as in Cinema 4D, but the animation in not working in Unity.
i've imported the animations in Unity in (.fbx) format and through Alembic plugin too, but still it's not worth it.
Is there another method to make it work in unity? @Nico-Duduf

**Comment by Nico-Duduf** [comment]
But.... This place is about After Effects and has nothing to do about Unity or Blender ;)

Though for your information, a standard way to exchange mesh animation like fluids is using Alembic, but I don't know Unity I can't help you more... Ask your question on a forum about Unity!
