### ISSUE TITLE
Change the path to a shape on the angle connector to make it easier to rotate and select in the viewer

### ISSUE THREAD

**Issue by joshsmithness** [Rainbox-dev/DuAEF_Duik#268]
# Environement

### Tool & Version
- Duik Bassel 16.0.2

### After Effects

- All
- English

### OS

- Mac OS 10.13

# What's the issue?

- Feature Request

Selecting and moving paths in the viewer window is a pain, so it would work better if the angle control was changed to a shape rather than a path!

### Error Location

- File:
- Line:

### Steps to reproduce

1. Create angle connector
2. Try to select in viewer
3. Its tricky!

### Expected behaviour

Easily be able to select and move the angle within the viewer window

### Actual behaviour

Not being able to select the angle in the window

**Comment by Nico-Duduf** [comment]
You're right, will do!

Thanks

**Comment by joshsmithness** [comment]
Hero! Thanks! Keep up the awesome work!

**Comment by Nico-Duduf** [comment]
done
