### ISSUE TITLE
Effector isn't created as a guide layer, would be nice if it was!

### ISSUE THREAD

**Issue by joshsmithness** [Rainbox-dev/DuAEF_Duik#278]
# Environement

### Tool & Version

- Duik 16.0.4

### After Effects

- CC2018 (15.0)
- English

### OS

- Mac OS 10.13

# What's the issue?

- Feature Request
Effectors aren't created as a guide layer, so appear in other comps and renders (obviously easy to make a guide layer yourself, but would be nice to have it already set as one!). Just a small thing but would be nice!

### Error Location

- File:
- Line:

### Steps to reproduce

1. creating effector
2. comes up as a normal layer rather than a guide
3. 

### Expected behaviour

Creates the effector as a guide layer

### Actual behaviour

Doesn't create a guide layer

**Comment by Nico-Duduf** [comment]
thanks for the feedback!
Will do ASAP
