### ISSUE TITLE
Bug: Tools Button in 16.1.0-Alpha1 does not show tools

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#280]
# Bug Report
Tools Button in 16.1.0-Alpha1 does not show tools

# Environement
16.1.0-Alpha1

### After Effects
- CC2018 (15.1.1)
- English

### OS
- Mac OS 10.13.6

![tools](https://user-images.githubusercontent.com/38455050/43291282-2a6481f2-9131-11e8-8dae-119308a3f2be.png)

**Comment by Nico-Duduf** [comment]
Very strange... I'll have to test here, and see if maybe it's only on mac.... I'll let you know what I find

**Comment by Nico-Duduf** [comment]
fixed

**Comment by reneandritsch** [comment]
Merci!
