### ISSUE TITLE
Galería interactiva de animaciones

### ISSUE THREAD

**Issue by Marioestrada96** [Rainbox-dev/DuAEF_Duik#281]
### Tool
- Duik

### Expected behaviour
- Poder guardar los valores de los keyframe de los controladores. para poder crear estados por ejemplo estado alegre o triste ( guardas estos valores en estados diferentes) y entre estos estados poder hacer una interpolacion. para facilitar el proceso de animación, ya que de este modo se podría tener siempre accesible los estados mas comunes como: alegria, tristeza, enojo, llanto, etc en correspondencia de que tan complejo sea el personaje y la cantidad de los controles pensándolo en un rigg para animaciones fluidas

Una referencia de como se ve la idea de una galería que almacene estados.
https://www.youtube.com/watch?v=vQxD8OOjh-I

**Comment by Nico-Duduf** [comment]
An animation (and rig) library is already planned #28 in a future version of Duik
