### ISSUE TITLE
Settings: by default in a subfolder instead of the "documents" folder

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/DuAEF_Duik#282]
Hi, could all json file in User Document put in one sub-folder, rather than lay at User Document directory?

**Comment by Nico-Duduf** [comment]
Hi,
You can already do this by changing the settings file in the settings panel of Duik: translation files are saved next to the settings file.

But I think all these files should be in a "Duik" subfolder by default, you're right, I'm going to change this.

**Comment by Nico-Duduf** [comment]
done
