### ISSUE TITLE
Can't translate "Size" and "Color #" in "Edit..." panel

### ISSUE THREAD

**Issue by eZioPan** [Rainbox-dev/DuAEF_Duik#290]
- Duik 16.0.4
Can't translate "Size" and "Color #" in "Rigging-Structures-Edit..." panel at "Export mode".
No item in translation json file; No use whether adding corresponding items.
Show as below.
![tranlationbuginstructureeditpanel](https://user-images.githubusercontent.com/10928361/43510502-7163ce52-95a8-11e8-8589-42189119c398.jpg)

**Comment by Nico-Duduf** [comment]
Yes, there are still a few items which are not translatable, I still have to track them. Thanks for the reminder ;)

**Comment by eZioPan** [comment]
Should I keep open issues for non-translatable items, or appending other non-translatable items in this issues, or stop tracking this kind issues?

**Comment by Nico-Duduf** [comment]
Let's keep this issue opened just to remind me I have to do this, but there's no need to list other no-translatable items, I know where they are.
You can already add them in the translation file though, this way they will be automatically be translated as soon as I've made them translatable. Just do not include the "#" in the "color" string ;)

**Comment by Nico-Duduf** [comment]
I'm sorry, I'll change what I just said, it's better to include the "#" in the "Color #" string, sorry ;)

I'm implementing this right now, and those strings will be translatable in the update I'm going to release today or tomorrow
