### ISSUE TITLE
Ae crashes with the autorig on CS6

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#297]
Ae CS6
see http://forum.rainboxprod.coop/viewtopic.php?f=11&t=532&p=1242

**Comment by Nico-Duduf** [comment]
I can't reproduce the crash here.

To anyone having this issue:
Can you check the box "enable javascript debugging" in the preferences of After effects, and the "Dev & Debug mode" in the settings of Duik, and then post here any error which are generated when using Duik on CS6?

Thanks

**Comment by zumek** [comment]
Having the same issue with Auto-IK on Win 7 pro, AE CS6, Duik 16.0.10 

Unfortunately it doesn't produce any error messages, just the APPCRASH dump.

Have also tried the Humanoid and same thing happens.

Thanks for any help!

**Comment by Nico-Duduf** [comment]
Hi @zumek, can you give me the exact version number of After Effects CS6 you're using? in the Help/About dialog you'll find the version starting with 11.x.x

I still can't reproduce here on any computer we have

**Comment by zumek** [comment]
Hi @Nico-Duduf, it's 11.0.0.378

Perhaps the issue is related to the Extendscrip toolkit do you think? The crash dump points to extendscript.dll as the culprit. The version of that I'm running is: 3.8.0.12 ExtendScript 4.2.12 ScriptUI 6.1.8.

Thank you for your effort - awesome tool! :)

**Comment by Nico-Duduf** [comment]
The only difference I see is on the version of After Effects, 11.0.0.378 is not the latest for CS6 (it is 11.0.4.2).

You should always use the latest build, in this case I think it should fix the issue. I don't see any other reason.

**Comment by Nico-Duduf** [comment]
We're going to stop fixing issues and supporting CS6, it's too much work for too few people. Also, this is a very old version of After Effects, and more and more features of Duik are not going to work with it.

It is strongly advised to update After Effects now.
