### ISSUE TITLE
DuBuilder: seems to be some bugs when #include lines end with ";"

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#3]

**Comment by oktomus** [comment]
Encore à jour ?

**Comment by Nico-Duduf** [comment]
aucune idée ^^ c'est vieux :D 
et je ne termine jamais mes includes avec un ; du coup je sais pas trop

**Comment by oktomus** [comment]
On supprimera ça plus tard alors ^^ 
Je ferrais un clean up des include si besoin

**Comment by Nico-Duduf** [comment]
fixed

DuBuilder now handles correctly #includes ending with a ;
