### ISSUE TITLE
Walk cycle with extracted controlles does not move arms and legs.

### ISSUE THREAD

**Issue by JacoboHansen** [Rainbox-dev/DuAEF_Duik#300]
# Bug Report

# Environement

### Tool & Version
- Duik 16.0.1-Alpha-5

### After Effects

- CC2018 (15.0)
- English

### OS

- Windows 10

# What's the issue?

I do not have hands and feet, only arms and legs, and have not tested if the problems persist if one does. When walk cycle is created with extracted Controllers, the armes and legs do not move. If the walk cycle is created in the precomp itself, the legs will move, but not the arms. 

### Steps to reproduce

1. Create a rig in a precomp. 
2. place that precomp in a composition and extract controllers
3. select controllers and create walk cycle

### Expected behaviour

Create a normal walk cycle, with arms and legs moving

### Actual behaviour

Creates a character standing still and bobbing up and down.

**Comment by Nico-Duduf** [comment]
The walk cycle cannot find the layers of the IK which are in the precomposition in this case ;

Fix: when the controllers are extracted, the link to the original controller must be kept in the marker data,
The IK/FK method then must check if the controller is linked to a controller in a precomp, and in this case get the data from the original controller.

functions to update:

- DuAEF.Duik.Animation.extractControllersFromComp 
- DuAEF.Duik.Animation.ik2fk
- DuAEF.Duik.Animation.fk2ik

**Comment by Nico-Duduf** [comment]
fixed
