### ISSUE TITLE
Error when extract controler with expression with footroll layer

### ISSUE THREAD

**Issue by Kuzobugi** [Rainbox-dev/DuAEF_Duik#305]
# Environement

### Tool & Version
- Duik 16.0.1-Alpha-5

### After Effects

- CC2018 (15.0)
- English

### OS

- Windows 10

# What's the issue?

- Bug Report

### Error Message

The project contains expression error
Expression disabled : goal world position of ... layer named FootRoll FootR is missing or does not exist.
Idem for GoalPosition.

### Error Location

- File: 
![image](https://user-images.githubusercontent.com/42748374/44675337-84533d80-aa30-11e8-8bd2-1a56f57ed767.png)

![image](https://user-images.githubusercontent.com/42748374/44675349-92a15980-aa30-11e8-94c6-346042840164.png)

- Line:

### Steps to reproduce

1. Create a rig with a footroll
2. Put the precomp in a comp
3. Extract the controlers with expressions

### Expected behaviour

It's working, it's just a bug report.

**Comment by Nico-Duduf** [comment]
fixed

**Comment by Kuzobugi** [comment]
Merci beaucoup :)
