### ISSUE TITLE
You can't do an ik if the first member has a parent.

### ISSUE THREAD

**Issue by lakpo** [Rainbox-dev/DuAEF_Duik#307]
# Environement

### Tool & Version

- Duik 16.0.5

### After Effects

- CC2018 (15.0)
- fr

### OS
- Windows 10

# What's the issue?

- Bug Report

### Steps to reproduce

after you parent the hip, try rigging the leg

https://i.imgur.com/0wYLW6z.gifv

**Comment by Nico-Duduf** [comment]
fixed
