### ISSUE TITLE
Info about Master Layer for Align Layers 

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#311]
### Tool & Version
- Duik 16.1.0-Alpha-2

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
Maybe it would be good to tell users in the Align section of the DUIK panel that the last layer selected is the Master Layer for the Align Tool.

**Comment by Nico-Duduf** [comment]
Good idea!

**Comment by Nico-Duduf** [comment]
done
