### ISSUE TITLE
Constraints Panel is missing tools

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#312]
# Environement
- Duik 16.1.0-Alpha-2

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Bug Report
The Constraints Panel is missing the tools past the “Parent across Comps…” mentioned in the DUIK help about the Constraints Panel. Please see screenshot. Also I don’t find the new Separate Dimensions Tool 

<img width="589" alt="bildschirmfoto 2018-08-30 um 18 52 28" src="https://user-images.githubusercontent.com/38455050/44866570-e6f14700-ac85-11e8-8b95-95dffc3aa1fe.png">

**Comment by Nico-Duduf** [comment]
Hi!

The UI has been (re)set to the "Rookie" mode which hides the most advanced tools, you'll have to go in the settings and set it back to "Normal" or "Expert" ;)

**Comment by reneandritsch** [comment]
Oh, I’m sorry!
