### ISSUE TITLE
Petit souci d'alignement copy/past anim

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#317]
petit souci au niveau de l'affichage, les layers ne sont pas alignés 👍 

[link](https://puu.sh/BuoUs/72798e4c0c.jpg)

# Environement

### Tool & Version
- Duik 16.0.4

### After Effects

- CC2018 (15.0)
- English

### OS

- Windows 10

**Comment by Nico-Duduf** [comment]
![screenshot_2018-09-17 afterfx_2018-09-13_18-51-02 jpg image jpeg 300 x 605 pixels](https://user-images.githubusercontent.com/8526542/45625276-c3533c80-ba8c-11e8-9b33-cbe673a63bf3.png)

**Comment by Nico-Duduf** [comment]
fixed
