### ISSUE TITLE
Absent: Controller  Absent: Structure

### ISSUE THREAD

**Issue by jangolake** [Rainbox-dev/DuAEF_Duik#329]
# Environement

### Tool & Version
- Duik 16.0.1-Alpha-5

### After Effects
CS6
Français

### OS

- Mac OS 10.11.6 El Capitan

# What's the issue?

- Bug Report
Quand j 'aimerais mettre une structure dans ma composition, par exemple si je clique sur "Hominoïde" (en mode standard), tous les calques ajoutés par duik apparaissent sur la composition, mais sous effet c'est inscrit "Absent: Structure" ou "Absent: Controller".
J'ai essayé de réinstaller plusieurs fois duik bassel, mais cela ne change rien.
La fenêtre duik se bloque facilement suite à une ou deux navigations.

### Error Location

- File:
- Line:

### Steps to reproduce

1. créer une composition avec plusieurs calques de solide et masque correspondant à un Hominoïde
2. fenêtre/duik bassel.jsx
3. setup structures/Hominoïde
4.magic is happening
5. calque duik, sous effet: Absent: Structure

**Comment by jangolake** [comment]
Dans les préférences "Autoriser les scripts à écrire des fichiers et à acceder au réseau" est coché.
J'ai essayé aussi avec "Activer le déblogage Javascript"
C'est la première fois que j'utilise duik, en espéarnt que ce problème va se résoudre, je vous remercies pour votre aide.

**Comment by Nico-Duduf** [comment]
Hello !

Ce n'est pas un bug, tout va fonctionner correctement même si certains effets sont notés "absent". C'est un souci inhérent à CS6, qui n'apparait pas sur le versions plus récentes.

**Comment by jangolake** [comment]
Super, merci pour la réponse si rapide, salutations sandra
