### ISSUE TITLE
parent link error "fromWorld"

### ISSUE THREAD

**Issue by msongz** [Rainbox-dev/DuAEF_Duik#331]
# Environement

### Tool & Version

- Duik 16.0.5

### After Effects

- CC2018 (15.1.2)
- English

### OS

- Mac OS 10.13.6

# What's the issue?

- Bug Report

### Error Message

layer to world matrix isn’t invertible in fromWorld.

[srt-duik-error.aep.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/2454692/srt-duik-error.aep.zip)

**Comment by msongz** [comment]
seems that the parent layer could not be scaled to 0% , or it will occur an error "layer to world matrix isn’t invertible in fromWorld"

**Comment by MeisterDerMagie** [comment]
Experienced this error today aswell. Duik v16.2.4
Is there a way to solve this?
