### ISSUE TITLE
FR: Indication for Connector Master Source in the panel

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#339]
### Tool & Version
- Duik 16.0.5

### After Effects
- CC2018 (15.1.2)
- English

### OS

- Mac OS 10.13.6

# What's the issue?
- Feature Request
Morgan shows a workflow in the Rigging Academy where he copy and pastes a Slider Control to shorten the rigging process. He points out that the panel only shows the word “Slider” which is still connected to the old “Master”.

It would be great to get more information on that slider in the Connector panel. Maybe in brackets underneath the Slider and/or a tool tip when hovering the mouse over the Master. The hint should indicate the layer the effect control belongs to so it would be easier for the user to identify where this effect is “buried”.

Thanks!

**Comment by Nico-Duduf** [comment]
good suggestion, I'm trying to improve the overall user experience for the connector in 16.1, I'll do something to address this issue!

**Comment by reneandritsch** [comment]
Thanks a lot!

**Comment by Nico-Duduf** [comment]
done
