### ISSUE TITLE
FR: Connector | Automatically enable layer visibility for children in replacement rig

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#341]
# Environement
### Tool & Version
- Duik 16.0.5

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Feature Request

### Expected behaviour
When rigging a replacement rig with a precomped layer (see screenshot) usually only one layer of the desired replacements is visible. It would be a workflow enhancement if DUIK automatically enables visibility for all children when they are connected to the opacities. Thank you!

![connector](https://user-images.githubusercontent.com/38455050/47343422-4d9f4980-d6a6-11e8-9c5a-caccb71b0e38.png)

**Comment by Nico-Duduf** [comment]
Quick and easy to do, and very useful ;) Will be done in the next alpha of 16.1

**Comment by reneandritsch** [comment]
Thanks a lot!

**Comment by Nico-Duduf** [comment]
done
