### ISSUE TITLE
You can transfer your program to OT.

### ISSUE THREAD

**Issue by 711GM** [Rainbox-dev/DuAEF_Duik#350]
I would really like to see your cool program, in the popular program OpenToonz. - https://github.com/opentoonz/opentoonz
![image](https://user-images.githubusercontent.com/40460266/47645139-27cfe400-db81-11e8-87ea-4ab688a55d25.png)

Here in these cartoons used this program. - https://www.youtube.com/watch?v=br94YgOdoBo

This is a popular program in which the Chibli studio worked. 

I have already made a request in OT. - https://github.com/opentoonz/opentoonz/issues/2350

Tell me what you need to agree? I can offer Money.

**Comment by Nico-Duduf** [comment]
Open toonz and After Effects are not the same program at all, this request is just impossible.
Also, Duik is a comprehensive tool set with a lot of stuff, you should be more precise about what features you'd need in OT, I'm sure some of Duik features already exist in OT.

You should request to the OT team the features from Duik you think should exist in OT

**Comment by 711GM** [comment]
I would very much like to move the Diuk myself. OT also has javascript and more. I would like to know what needs to be done so that the OT could support Diuk. I understand that this sounds like not possible and difficult, but if you understand well, then it is all the same possible. I have already talked with one programmer, he says that it is possible, but he does not want to work on it.
