### ISSUE TITLE
FR: Button to select Bones

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#352]
### Tool & Version
- Duik 16.0.9

### After Effects

- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Feature Request

### Use
Dear Nicolas, it might be convenient to also have a button that lets the user select all bones in a rigged object. Maybe this could even be paired with the “Select Structures” button not to add an additional button to the UI. The name could be “Select Structures/Bones” which might also have an options dialogue in which the user could select/deselect structures and/or bones depending on what should be selected. This way the bones could also be hidden quickly with the Show/hide button.

**Comment by Nico-Duduf** [comment]
Hum... I'm even thinking that a small separate panel could include all the select/show-hide buttons for all types of layers.

I'll see what could be best

**Comment by reneandritsch** [comment]
Thanks for considering this, the show/hide panel sounds interesting.

**Comment by Nico-Duduf** [comment]
done in the additionnal panel for the bones.

I still have to build a show/hide panel
