### ISSUE TITLE
FR: Modifier key for Button “Show/hide”

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#353]
### Tool & Version
- Duik 16.0.9

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Feature Request

### Usage
Dear Nicolas, when rigging separate body parts not all structures are necessarily visible all the time. So when selecting all structures with the “Select structures“ Button all structures are selected while they stay partly visible. Now when hitting the “Show/hide” Button all visible structures are hidden and the invisible ones are shown. 

![show-hide](https://user-images.githubusercontent.com/38455050/47704847-4091d580-dc25-11e8-8c21-fd4aac82a487.gif)

It would be great if it was possible to hold the “ALT” key when pressing the “Show/hide” Button so all structures would be set to visible. That would streamline the process and the user would not have to leave the DUIK panel to set the different visibilities to the same state. Thanks!

**Comment by Nico-Duduf** [comment]
Well, this should be the default behaviour I think ^^
I'll do this, and maybe keep the current behaviour with the alt key ;)

**Comment by reneandritsch** [comment]
Thanks!

**Comment by Nico-Duduf** [comment]
done

The "invert" behaviour is still available holding the Alt button, and works also with controllers and bones
