### ISSUE TITLE
UI: Whole button clickable would be great

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#357]
# Environement
### Tool & Version
- Duik 16.0.9

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Feature Request

### Enhancement suggestion
Dear Nicolas, at the moment the user has to click directly on the icon or the description of the button to activate a function. Working with DUIK Bassel I experienced quite often that my cursor was not directly on those items and I wished that the whole width of the button was clickable. Please see the screencaptue …

It is especially puzzling that a click has no effect on the button if the cursor is between the icon and the type.

![click](https://user-images.githubusercontent.com/38455050/48662544-d5009280-ea83-11e8-9762-e95223623369.gif)

**Comment by Nico-Duduf** [comment]
fixed!

I've wanted to do this for a long time, and decided to have a look at it again. Found a solution in 5minutes, thanks 😄 

It still won't work on CS6, but with all more recent versions, it's ok :)

**Comment by Nico-Duduf** [comment]
- [ ] same fix for checkboxes
- [ ] selector
- [ ] layerselector
- [ ] compselector

**Comment by Nico-Duduf** [comment]
I can't do it with the layer/comp selectors (it would crop the name longer than... 4 characters) but it works better now for standard buttons, dropdown selectors and checkboxes

**Comment by reneandritsch** [comment]
Looking forward to trying it. Thank you for your efforts!
