### ISSUE TITLE
Auto-Parent does not work if selection contains already parented layers

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#359]
# Environement
- Duik 16.1.0-Alpha-4

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Windows 10
- Mac OS 10.13.6

# What's the issue?
- Bug Report

### Steps to reproduce

1. Parent layers either manually or with Auto-Parent 
2. Select layers (also parented ones)
3. try to parent to a new layer

### Expected behaviour
Layers should be parented to the new (last) layer selected

### Actual behaviour
nothing happens – please see screen capture

![auto-parent](https://user-images.githubusercontent.com/38455050/48677088-0191d880-eb70-11e8-99a7-e6c1233d67ac.gif)

**Comment by Nico-Duduf** [comment]
Thanks for the feeedback!

**Comment by Nico-Duduf** [comment]
fixed
