### ISSUE TITLE
It seems some translations (chinese) are not correctly loaded

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#362]

**Comment by Nico-Duduf** [comment]
works in 16.0.10, check in 16.1.0 alpha

**Comment by eZioPan** [comment]
Button label "Parent constraint" not loaded correctly in 16.0.10.
In the translation file, this item seems still named "Parent Link". Manually modifying to "Parent constraint" make no difference.

**Comment by Nico-Duduf** [comment]
thanks for the feedback, I'll check this for the other languages.
I'll have to update the translation files for the upcoming 16.1.0 version anyway, I'll let you know here as soon as it's done.

**Comment by Nico-Duduf** [comment]
this should be fixed in 16.1 which will be out in a few days.
If you want to have a hand on the translations of this new version, check the translation file of the 16.1.0 branch there:
https://github.com/Rainbox-dev/DuAEF_Duik/tree/16.1.0/src/tools%20(ScriptUI)/Duik/translation
just grab the Duik Bassel_zh.json file
and have a look in this folder to get the latest version of Duik to test it:
https://github.com/Rainbox-dev/DuAEF_Duik/tree/16.1.0/Release/Duik/Duik%20Bassel%20(16)
(i'm going to add the 16.1.0 beta and RC in a few minutes)
