### ISSUE TITLE
FMR: Renaming of the wiggle option “unique” to “unified”  

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#376]
### Tool & Version
- Duik 16.1.0-Beta

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
Dear Nicolas, reading the DUIK manual for the wiggle tools I think the “Unique Control” should be renamed to “Unified Control”. This describes it better I guess.

**Comment by Nico-Duduf** [comment]
Done! :) Thanks
