### ISSUE TITLE
Uncaught JavaScript exception : JSON.parse

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#406]
see http://forum.rainboxprod.coop/viewtopic.php?f=6&t=624&p=1595

**Comment by gordielachance** [comment]
Still have that same issue (was working great before), at line 548 JSON.parse...
I did remove all what I found related to you within 
C:\Users\XXX\AppData\Roaming, but it didn't work.
Windows 10 here.
Thanks.

**Comment by gordielachance** [comment]
Finally worked not by deleting files in

> C:\Users\XXX\AppData\Roaming

but by deleting the settings file

> C:\Users\XXX\Documents\Duik_settings.json

**Comment by didrip** [comment]
Encountered same issue after DUIK auto-update, I confirm the fix from @gordielachance :

=> delete the file `C:\Users\XXX\Documents\Duik_settings.json`

- DUIK v16.0.12
- After Effects CC 2019
- Windows 1809

**Comment by Nico-Duduf** [comment]
Thanks for the feedback ; I can't do much about the issue in Duik, but the next update will include a way to reinitialize the settings and easily fix it (without the need to find and delete any file used by duik):
http://duaef-docs.rainboxlab.org/Guides/Duik/install-duik.html#fix-uninstall-duik
