### ISSUE TITLE
FR: Animation Keys UI: Please add slider for Velocity

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#411]
# Environement
### Tool & Version
- Duik 16.0.1-RC1

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# Feature Request
Please add a slider for Velocity as well – it is so convenient :-)

![slider](https://user-images.githubusercontent.com/38455050/51806217-9f440b00-2277-11e9-8eb3-e278238eb74d.png)

**Comment by reneandritsch** [comment]
I thought more about it and – well – velocity can be any value so it is difficult to project the range onto a slider. I just got carried away … I think you can archive this request.

**Comment by Nico-Duduf** [comment]
I'd like to find a way though...
Maybe adjusting the behaviour depending on the type first selected property; if it's spatial/an angle/a percent it may be not to hard to find useful min and max values.
Simple sliders may be trickier, but Duik could also scan the property, measuring current velocities of the animation to deduce user-friendly values.
I'm thinking as I'm typing, and I think this can actually be a nice way to do this!

**Comment by reneandritsch** [comment]
You are a genius! Curious what you come up with. But please take your time ...

**Comment by Nico-Duduf** [comment]
I managed to do it!

The tool adjusts the velocities relatively to what the velocities would be if the keyframes were linear.
The result is pretty intuitive: 0%, no velocity at all (full stop), 100% is the same as setting the keyframe to "Bezier continuous", -100% is the same speed, but inverting the motion (works only with single dimension properties), 200% is twice the bezier continuous, etc.

Using it seems nice!
I'll share the update tomorrow on patreon

Thanks again for your suggestions ;)

**Comment by reneandritsch** [comment]
Amazing! Looking forward to trying it …
