### ISSUE TITLE
BR: Animation Keys – Values bigger 100% for influence 

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#412]
# Environement
### Tool & Version
- Duik 16.0.1-Alpha-5

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Bug Report

### What’s happening
It is possible to enter values bigger than 100% for velocity (just discovered that by chance). If done it would be great to have it set to the maximum value of 100%

Is it possible to right align the numbers of influence and velocity? That might enhance the look of the interface. Please see screenshot.

![values](https://user-images.githubusercontent.com/38455050/51806299-a7507a80-2278-11e9-9244-67781878edee.png)

**Comment by Nico-Duduf** [comment]
will do!
thanks

**Comment by Nico-Duduf** [comment]
fixed

**Comment by reneandritsch** [comment]
Thank you!
