### ISSUE TITLE
DUIK rigs break randomly

### ISSUE THREAD

**Issue by planetfrenzy** [Rainbox-dev/DuAEF_Duik#413]
# Bug Report

software: AE cc 2017, Mac, (14.2.1)
I created several rigs, 
They worked,
- a few problems
--- suddenly could not create bones any more- clicking the bones button did nothing,
Restart after effects, created bones, clicked on one and stage went black. 
Then same thing happened when I tried creating an IK rig afterwards.
-- also experience: The bone layers were being controlled, but the Image layer (with the puppet effecdt on it) was not.
-- restart Mac, restarted AE. Problem persisted. Deleting IK elements allowed the stage to become visible again at least (comp setup not lost, or at least I thought). But any re-attempt in this document cause the bug to resurface.
-- started a NEW document. DUIK seemed to perform again
-- BUT it is happening again. 

This product is such a great thing for me.... should I give up and become a turnip waxer instead. Life is precarious enough. //

Thanks muchly,
m

**Comment by Nico-Duduf** [comment]
Hi!

Thanks for your feedback.
It seems you're reporting different issues, concerning bones, IK.
Could you break this down into several distinct issues?

i.e. one for the bones not being created (and be specific about how this happens, maybe include a screenshot or a project file) another for the IK (what did you use, IK, or Auto-rig, for which kind of limb, with or without structures ? etc), another one for the bones not controlling what they should (is it with a path or with the puppet tool, etc?)

Thanks.

**Comment by planetfrenzy** [comment]
Hi Nicolas,
Thank you so much for reaching back. I need to remove this comment. I am 90% sure now I was just being spastic about my own errors :/ . I apologize for it.
The tool is super. Thanks for it.
MP

**Comment by Nico-Duduf** [comment]
No problem ;)
Thanks!
