### ISSUE TITLE
2D Camera feature influence has no effect

### ISSUE THREAD

**Issue by nickmadedesign** [Rainbox-dev/DuAEF_Duik#417]
# Environment
- Duik 16.0.11

### After Effects
- CC2019 (16.0.1 Build 48)
- English

### OS
- Mac OS 10.14.2

# What's the issue?
The 2D Camera feature doesn't seem to have any effect (influence) on layers parented to nulls
![2019-02-05 21-02-47 2019-02-05 21_16_17](https://user-images.githubusercontent.com/40440324/52316834-55e86f80-298b-11e9-84d8-94e835feacc2.gif)
. 

### Steps to reproduce

1. Create 3 shape layers named fg, mg, bg
2. Parent mg to L02 Camera layer, the bg to L01, and the fg to L03.
3. Set a keyframe on L02 Camera layer for Horizontal Pan at 0, advance any time, set a keyframe to move the shape layers off the stage.
4. Bang head on keyboard because it's been a long day.

### Expected behaviour
Move at a different rate based on null influence per the shape layer (i.e. default 2d multiplane)

### Actual behaviour
The influence value has no effect.

**Comment by Nico-Duduf** [comment]
Hi Nick,

This is normal, to have a multiplane effect you just have to use the position of the controller ;)
The pan is there to simulate a rotation of the camera, and this is what happens visually.

https://rainbox-dev.github.io/DuAEF_Duik/Guides/Duik/camera-2d/

**Comment by nickmadedesign** [comment]
Hey Nico, I'm going to blame it on a long day. The silly thing is I read "Move the layer to truck" many times but it didn't register in my brain :)

Thanks!
