### ISSUE TITLE
Bug Animation Tools: Locked Influence Values need two clicks to be set with presets

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#419]
# Environement
### Tool & Version
- Duik 16.1.0-RC2

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Bug Report

### Steps to reproduce
Dear Nicolas, working with the animation tools I’m not sure if this is an intended behavior or a bug. When the influence is locked and there are two keyframes selected I set a value with a preset. Only one handle changes accordingly. Using the slider both handles change at the same time.

### Expected behaviour
The tangents of the keyframe influence should change for both values in the graph editor at the same time

### Actual behaviour
The tangents of the keyframe influence only change for one value in the graph editor

[Screencaptures.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/2844547/Screencaptures.zip)

**Comment by Nico-Duduf** [comment]
fixed!

**Comment by reneandritsch** [comment]
Thank you!
