### ISSUE TITLE
UI Animation Tools: Reversing preset values for incoming handle and velocity on the left

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#420]
# Environement
### Tool & Version
- Duik 16.1.0-RC2

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Enhancement Request

### Expected behaviour
Hi Nicolas, I think it might be more intuitive for the user if the preset values on the left side are also mirrored like the sliders. As the slider goes from lower values from the center to higher values on the left side of the interface. So instead of having 33,50,75 on the left side it would be better to have 75,50,33 in my opinion. This would also give a nice indication for the slider.

![influence_ui](https://user-images.githubusercontent.com/38455050/52471623-9addf300-2b91-11e9-8e41-01996c13abc2.png)

**Comment by Nico-Duduf** [comment]
done

**Comment by reneandritsch** [comment]
Thanks a lot!
