### ISSUE TITLE
Auto-create structures from shape layer does not work for me

### ISSUE THREAD

**Issue by planetfrenzy** [Rainbox-dev/DuAEF_Duik#431]
Hello,
I am following along with your very excellent tutorial on tuto.com and now trying to use that very useful way of creating structures from shape layer. I have tried many times but always a new structure is created, as it would be without a shape layer, and the shape layer remains in timeline (not removed as would be the expected behaviour). 
I can't see what I could be doing wrong but are the any 'gotchas' I can test for perhaps?
Kind Regards,
MP

**Comment by Nico-Duduf** [comment]
You have to use the version of Duik provided with the tutorial, not the public one ;)

**Comment by planetfrenzy** [comment]
Terrific. Thanks very much.

**Comment by planetfrenzy** [comment]
Hi. Me again. I have installed the plugin that came with the tutorial files- Duik Bassel_16.1.0-Beta3.jsx & duik_limbs_hand.ffx but it does not work either. Actually hangs After Effects up (the magic is happening icon shows when attempting the process :( )  or does nothing at all. I removed the old version but left the ffmeg, Help folder in my UI Panels but tried removing the Tools folder (as well as keeping it in). Anyway if there is a fix it would be great. Really intelligent addition to already intelligently designed software, man. I'll send fan mail some other place though :)
Regards,
MP

**Comment by Nico-Duduf** [comment]
Weird.
Can you "enable javascript debugging" in the After Effects preferences and post a screenshot of the editor which is shown when the script stops working?

you can also try this version: https://github.com/Rainbox-dev/DuAEF_Duik/raw/16.1.0/Release/Duik/Duik%20Bassel%20(16)/Pre-Release/Duik%20Bassel_16.1.0-RC2.zip
and let me know if this one works

thanks!

**Comment by planetfrenzy** [comment]
Hi Nicolas,

Attached are screen shots of editor and debugger window.

Cheers/thanks,
Mark Parenteau





RedHorse Interactive
design | move | interact
C 437-990-2142

**Comment by Nico-Duduf** [comment]
Attachments are not sent to githb by mail, can you log in the website directly to post it please? (and try the version I've linked)

thanks

**Comment by planetfrenzy** [comment]
Oh. Will do.
I was just continuing with that version but then it seems even the autorig IK isn’t working either, so you know.
I am ok with previous version until things get worked out, but will also try the version you just sent so we know about that as well.

Cheers,
mrk

**Comment by planetfrenzy** [comment]
![screen shot 2019-02-24 at 9 25 46 am](https://user-images.githubusercontent.com/47117626/53301732-86058e80-3824-11e9-92c5-351b346e1442.png)
![screen shot 2019-02-24 at 9 25 27 am](https://user-images.githubusercontent.com/47117626/53301733-86058e80-3824-11e9-9660-8a4c70de21e9.png)

**Comment by planetfrenzy** [comment]
I just tried the version Duik Bassel_16.1.0-RC2. With same results. (
![screen shot 2019-02-24 at 11 12 38 am](https://user-images.githubusercontent.com/47117626/53301797-265bb300-3825-11e9-8d0d-d8ac169c423f.png)
![screen shot 2019-02-24 at 11 12 25 am](https://user-images.githubusercontent.com/47117626/53301798-265bb300-3825-11e9-85b3-dd69d10de6a1.png)

**Comment by Nico-Duduf** [comment]
There was an issue with versions of Ae older than 15. Fixed
