### ISSUE TITLE
frame guide expression error on cc2019

### ISSUE THREAD

**Issue by msongz** [Rainbox-dev/DuAEF_Duik#439]
camera-framing guides:

`if (effect("Frame")(4).value == 1) 0 else effect("Frame")(6);`

-->

`if (effect("Frame")(4).value == 1) {0} else {effect("Frame")(6)};`

---
`if (effect("Frame")(4).value == 2) 0 else effect("Frame")(6);`

-->

`if (effect("Frame")(4).value == 2) {0} else {effect("Frame")(6)};`

**Comment by msongz** [comment]
i am not very clear about how to edit the ffx.jsxinc

**Comment by Nico-Duduf** [comment]
Hi, thanks for your feedback!

Don't worry, I'll fix this tomorrow. The process is a bit tedious, the .ffx has to be updated using Ae (CS6 for better compatibility), and then converted to a .ffx.jsxinc using a converter script ( located in src/Tools)

**Comment by msongz** [comment]
thanks! it heard really tedious 🙃

**Comment by Nico-Duduf** [comment]
fixed!
