### ISSUE TITLE
BUG Animation Tab: Pick Ease and Velocity does not work

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#440]
# Environement
### Tool & Version
- Duik 16.1.0-RC4

### After Effects
- CC2018 (15.1.2)
- English

### OS
- Mac OS 10.13.6

# What's the issue?
- Bug Report

### Expected behaviour
The “Pick Ease and Velocity from Key” should pull in the values  

### Actual behaviour
Nothing happens

![pick](https://user-images.githubusercontent.com/38455050/54026674-faceb600-419e-11e9-9dd2-2f2ec33f43c4.gif)

**Comment by Nico-Duduf** [comment]
fixed
