### ISSUE TITLE
connector : 2D slider error

### ISSUE THREAD

**Issue by msongz** [Rainbox-dev/DuAEF_Duik#441]
# Environement

### Tool & Version

- Duik 16.1.0-rc4

### After Effects

- CC2019 (16.0)

### OS

- Mac OS 10.13.6

# What's the issue?

- Bug Report
![](https://ws3.sinaimg.cn/large/006tKfTcgy1g110nbb10oj309105bt8w.jpg)
![](https://ws1.sinaimg.cn/large/006tKfTcgy1g110q7ewurj30es0863z7.jpg)

when clicking the 2D slider in debug mode, it prompts error.

**Comment by Nico-Duduf** [comment]
weird.
Thanks, I'll have a look at that asap

**Comment by Nico-Duduf** [comment]
fixed
