### ISSUE TITLE
Review naming of Parent Constraint in the Effects Panel 

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#446]
# Environement

### Tool & Version
- Duik 16.1.0-RC4

### After Effects
- CC2019 (16.1)
- English

### OS
- Mac OS 10.14.4

# What's the issue?
- Naming issue

### Expected behaviour
The effect for the Parent Constraint should also be named Parent Constraint in the Effects Panel. At the moment it is called “Parent Link”

It is just a minor thing but might lead to confusion for some users.

<img width="334" alt="parent_link" src="https://user-images.githubusercontent.com/38455050/55650316-a2162b80-57e5-11e9-8b2a-050332ca2279.png">

**Comment by Nico-Duduf** [comment]
fixed
