### ISSUE TITLE
Kleaner: review naming of Clean Keyframes

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#447]
# Environement

- Duik 16.1.0-RC4

### After Effects
- CC2018 (16.1)
- English

### OS
- Mac OS 10.14.4

# What's the issue?
Maybe it would be more obvious to users if instead of “Clean Keyframes” the feature would be named after what it really does “Remove unnecessary keyframes”.

Thanks, René

![clean](https://user-images.githubusercontent.com/38455050/55673737-19ae8e00-58ac-11e9-9ba1-34a39627ab1e.jpg)

**Comment by Nico-Duduf** [comment]
fixed
