### ISSUE TITLE
Extract 3D Controler

### ISSUE THREAD

**Issue by Kuzobugi** [Rainbox-dev/DuAEF_Duik#448]
Then i put a controler in 3 dimension and want to extract him, the Extract fonction doesn't work.

# Environement

### Tool & Version
- Duik Bassel-16.1.0-RC4

### After Effects

- CC2019 (16.1.1)
- English

### OS

- Windows 10

# What's the issue?

- Bug Report

### Error Message

No error message
### Steps to reproduce

1. Make a precomp with a controler
2. Make it 3D
3. Extract in a new comp with Extract Tool

### Expected behaviour

To extract the controler in 3D.

### Actual behaviour

Nothing.

**Comment by Nico-Duduf** [comment]
fixed
