### ISSUE TITLE
Walk Cycle: Error at line 1 in property 'L footroll'

### ISSUE THREAD

**Issue by javiermherreros** [Rainbox-dev/DuAEF_Duik#473]
# Environement

### Tool & Version
- Duik 16.0.11

### After Effects

- CC2019 (16.1.1)
- English

### OS

- Windows 10

# What's the issue?

- Bug Report

### Error Message

Error at line 1 in property 'L footroll' of layer 1 ('C/ Walk Cycle') in comp 'boy left rig'
Error: Undefined value in expression (colud be an out of range array subscript?)
### Error Location

- File: raining.aep
- Line: boy left walkCycle (comp)

### Steps to reproduce

1. import model from AI with Overlord
2. create hominoid structure and rig character
3. create an automated walk cycle

### Expected behaviour

create a walk cycle
### Actual behaviour

create a walk cycle but the arms don't move
[rainig.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3101457/rainig.zip)

**Comment by Nico-Duduf** [comment]
fixed
