### ISSUE TITLE
Can't uncheck "display latest news" or "chack for updates at startup"

### ISSUE THREAD

**Issue by Jissse** [Rainbox-dev/DuAEF_Duik#483]
# Environement
### Tool & Version

- Duik 161.0 RC1

### After Effects
- CC2019
- English

### OS
- Windows 10

# What's the issue?
Can't uncheck "display latest news" or "chack for updates at startup" in the options panel

### Expected behaviour
Getting rid of the annoying popup

### Actual behaviour
Being annoyed by the popup

**Comment by Nico-Duduf** [comment]
fixed
