### ISSUE TITLE
animation presets -> undefined

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#492]
coucou !
petit sushi ici :

https://puu.sh/E3y9R/327d4dc17a.png

Lorsqu'on clique sur les presets ça fait "undefined"

bisous

**Comment by Nico-Duduf** [comment]
Hum je n'arrive pas à reproduire le problème de mon côté....
Tu pourrais me faire une capture vidéo, où je vois quelle(s) clefs tu sélectionnes, etc ?

**Comment by Nico-Duduf** [comment]
https://puu.sh/E4dLR/87ec67bdc0.mp4
