### ISSUE TITLE
Duik Bassel.1 help links open folders in Finder (Mac) instead of content page

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#494]
# Environement
### Tool & Version
- Duik 16.1.

### After Effects

CC2019
- English

### OS
- Mac OS 10.14.6

# What's the issue?
- Bug Report

### Steps to reproduce
1. Start from the help index file
2. Click help topic
3. 

### Expected behaviour
topic page should open up

### Actual behaviour
Folder of topic page is opened up

![help](https://user-images.githubusercontent.com/38455050/62838915-d8c3ed00-bc82-11e9-81a5-2301cd8ebb03.gif)

**Comment by Nico-Duduf** [comment]
hum strange... I'm afraid this is the way Safari works with offline html. Is it the same with Chrome or Firefox? I'll have a look at this on a mac ASAP but I'm not sure what I can do about it

**Comment by Nico-Duduf** [comment]
well actually there's the same issue on windows, because the links lack the "index.html" part which is needed for offline files...
I'll see if I can fix this
