### ISSUE TITLE
Controllers options

### ISSUE THREAD

**Issue by Jissse** [Rainbox-dev/DuAEF_Duik#496]
# Environement

### Tool & Version
- Duik Bassel .1

### After Effects

- CC2020
- English

### OS

- Windows 10

# What's the issue?

- Feature Request

### Steps to reproduce

As it's a different type of controller, creating a parent null with ctrl+click in the controllers panel should be different than the others controllers: null placed above the selected layers and not on top of the comp. Also the scale should not be locked by default.

**Comment by Nico-Duduf** [comment]
done
