### ISSUE TITLE
Walk cycle expressions errors with AE 16.1.2

### ISSUE THREAD

**Issue by bgekun** [Rainbox-dev/DuAEF_Duik#499]
# Bug Report
The walk cycle doesn't work properly : the arms don't swing and expressions are disabled

# Environement
Duik Bassel 16.0.12

### After Effects
CC2019 16.1.2
- English

### OS
- Mac OS 10.14.5

# What's the issue?

### Error Message
Walk cycle Error at line 1 in property 'R footroll' of layer ('C Walk Cycle') in comp 'perso_1'. 
Undefined valued used in expression (could be an out of range array subscript?), an expression was disabled as a result of an error.

### Error Location

- File:
- Line:

### Steps to reproduce

1. Import AI character in After Effect
2. Rig with Duik Bassel
3. Apply Walk Cycle

### Expected behaviour
walk cycle with swinging arms.

### Actual behaviour
Arms don't swing.
[Anim1_190819_folder.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3516922/Anim1_190819_folder.zip)

**Comment by Nico-Duduf** [comment]
Thanks for your feedback!

This has been fixed in Duik Bassel.1, the next version, which will be available soon ;)
