### ISSUE TITLE
Cannot download Duik - 504 Gateway problem

### ISSUE THREAD

**Issue by PrzemoDev** [Rainbox-dev/DuAEF_Duik#504]
https://rainboxprod.coop/en/tools/duik/ does not working - I get 504 Gateway Time-out. Is there any other way to download Your after effects rigging tool?

**Comment by Nico-Duduf** [comment]
Yes, our websites are down, I hope it will be fixed soon...

These links should still work:
https://rainboxprod.coop/downloads/duik/Duik_Bassel_WIN.zip
https://rainboxprod.coop/downloads/duik/Duik_Bassel_MAC.zip
