### ISSUE TITLE
Error dialog box

### ISSUE THREAD

**Issue by Seabat7** [Rainbox-dev/DuAEF_Duik#517]
**Describe the bug**
After updating to the latest DUIK script I now get an error message. UNABLE TO EXECUTE SCRIPT AT LINE 1. EVENT MANAGER IS UNDEFINED
**To Reproduce**
1. Open After Effects
2. Pop up window with error and the menu is uber large in the window
![Image 9-11-19 at 2 58 PM](https://user-images.githubusercontent.com/55208968/64726654-1b0c6400-d4a5-11e9-9147-a00add9fe4ab.jpg)
![Image 9-11-19 at 2 58 PM](https://user-images.githubusercontent.com/55208968/64726664-21024500-d4a5-11e9-87b3-2affde734297.jpg)

3. 

**Error description, if any**
File: 
Line number: 1
Error message: 
EvenManager is Undefined

**Expected behavior**
No error message

**Screenshots**

**System (please complete the following information):**
 - OS: Mac OS 10.14.6 
 - Version of After Effects: V 16.1.2
 - Version of Duik: 16.1.0

**Additional context**

**Comment by Nico-Duduf** [comment]
Thanks for the feedback. I've never seen this error before, I'm going to investigate

**Comment by Seabat7** [comment]
If I can help in anyway let me know. It happens every time I load AE

**Comment by Nico-Duduf** [comment]
What do you mean, Duik is not in the scripts menu?
