### ISSUE TITLE
Motion Blur Bug with Parent Constraint

### ISSUE THREAD

**Issue by andreastanner** [Rainbox-dev/DuAEF_Duik#520]
**Describe the bug**
Hi there
I noticed that in the new version of DUIK (16.1.1) is still the bug, that motion blur is not correctly working together with the parent constraint? I tried to increase the motion blur precision but nothing happens... it still looks like there are too few substeps in mobo.

Thanks very much!

**Comment by Nico-Duduf** [comment]
fixed
