### ISSUE TITLE
Activating “Bounce” in Kleaner causes expression error

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#527]
**Describe the bug**
After activating the Bounce option there is an error shown in the expression

**To Reproduce**
1. User Kleaner
2. Activate Bounce in Overlap (I think should be names Overshoot)

**Error description, if any**
see screenshot
![error](https://user-images.githubusercontent.com/38455050/66232502-415ea180-e6e9-11e9-957e-54e9d471fa72.png)
 

**Expected behavior**
No error and bounce behavior.

**Screenshots**
![bounce](https://user-images.githubusercontent.com/38455050/66232602-8387e300-e6e9-11e9-8e57-00918c2dfd2e.gif)

**System (please complete the following information):**
 - OS: 10.14.6
 - Version of After Effects: 16.1.3
 - Version of Duik: Kleaner

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, I know what's wrong, it's a quick fix.

**Comment by Nico-Duduf** [comment]
fixed
