### ISSUE TITLE
change UI from standard to expert will not update the new UI

### ISSUE THREAD

**Issue by msongz** [Rainbox-dev/DuAEF_Duik#530]
**Describe the bug**

**To Reproduce**
1. click on the setting icon
2. change UI from standard to expert by 1 click
3. click apply

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: macOS
 - Version of After Effects: 16.1.3
 - Version of Duik: 16.1.2

**Additional context**

**Comment by msongz** [comment]
restart the script will update the setting and works fine

**Comment by Nico-Duduf** [comment]
Do you have the issue with the dev folder from Github and using symlinks or copying all the different files to scriptUI Panels?
In this case it's normal, the apply button won't find the right file to reload,
But when using the public build all in one file, it should work correctly; in this case it is indeed a bug

Let me know!

**Comment by msongz** [comment]
yes! i use the symlink to make DUIK works at the commit HEAD

**Comment by Nico-Duduf** [comment]
In this case it's ok
I'm closing this issue, but I keep in mind it would be nice to make it work when files are separated/with symlinks ;)
