### ISSUE TITLE
The Constraints panel

### ISSUE THREAD

**Issue by mamoun86** [Rainbox-dev/DuAEF_Duik#535]
**Describe the bug**

**To Reproduce**
1. Open after effects
2. Drag 'slider Constraints' 
3. Pop up window with Script Alert

**Error description, if any**
File: 
Line number: 23671
Error message: Property

**Expected behavior**

**Screenshots**
![unknown](https://user-images.githubusercontent.com/40662938/66548029-1f31ad00-eb49-11e9-89af-9321b945249a.png)

**System (please complete the following information):**
 - OS: WIndows 10
 - Version of After Effects: 16.1.3.5
 - Version of Duik: 16.1.2

**Additional context**

Thanks

**Comment by Nico-Duduf** [comment]
fixed in 16.1.3 available very soon

**Comment by mamoun86** [comment]
Thank you
