### ISSUE TITLE
DuAEF.DuAE missing properties in Duik16_api

### ISSUE THREAD

**Issue by Octopodo** [Rainbox-dev/DuAEF_Duik#539]
**Describe the bug**
I get undefined with some properties of DuAEF.DuAE like DuAEF.DuAE.Presets or DuAEF.DuAE.PseudoEffects. This happens simply by using the sample script, without any additional code. I've tryed with oder api methods and I get undefined on several DuAEF.DuAE properties. 
 

**To Reproduce**
1. Create a folder
2. Add Duik16_api.jsxinc file
3. Create new .jsx file in the same folder
4. Paste sample script on the new file: 
`  (function(thisObj) {
    #include 'Duik16_api.jsxinc'
    Duik.structures.mammal();
  })(this);`
5. Run vscode debugger.

**Error description, if any**
File: Duik16_api.jsxinc
Line number: 3897
Error message:  undefined is not an object

**Expected behavior**
Th api creates a mammal structure in the current composition

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 16.1.1 
 - Version of Duik:

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, I'll have a look at that by the end of the week

**Comment by Nico-Duduf** [comment]
Fixed

the error with actually in the doc, not in the API ^^
You need to initialize DuAEF before using the API, here's the new example:

```
//encapsulate everything to avoid global variables !important!
(function(thisObj) {
    //include the API
    #include 'Duik16_api.jsxinc'
    //Now the Duik API is available in the Duik object, and DuAEF is also available.

    //We need to initialize DuAEF before using it. You must provide a script name and version.
    DuAEF.init("Your Awesome Script Name", "1.0.2");

    //Now you can create your UI if any, and initialize what you need.
    //DuAEF can be of great help, it has a lot of methods for creating the UI, handle After Effects, and more.
    //Read the reference at duaef-reference.rainboxlab.org

    //When everything is ready and before using the Duik API,
    //We need to tell DuAEF we're entering run state so it can finish to prepare its stuff.
    DuAEF.enterRunTime();

    // Create a hominoid structure
    // The whole API is contained in the Duik object
    Duik.structures.mammal();
    //Have Fun!
})(this);
```

**Comment by Nico-Duduf** [comment]
The doc is updating and will be available soon. The API has a new build too with a few fixes and improvements from Duik Bassel.2

**Comment by Octopodo** [comment]
Awesome, thanks!
