### ISSUE TITLE
parent Across Comps doesnt work.

### ISSUE THREAD

**Issue by FKMONKEY** [Rainbox-dev/DuAEF_Duik#541]
**Describe the bug**
parent Across Comps doesnt work. it creats LOC layers and but it doess not work. 
**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 
 - Version of Duik: 

**Additional context**

**Comment by Nico-Duduf** [comment]
From my tests here, everything works correctly.

Can you give a bit more details (for example by filling the template of the bug report). I'd need at least the version of Duik and of After Effects.

Are you trying to parent from a precomp to a parent comp or the opposite?
What kind of layers are you trying to parent (shape, footage, text...)?
Are they 3D Layers?
