### ISSUE TITLE
Head Controller doesn't work with zero function.

### ISSUE THREAD

**Issue by AaronEcthelion** [Rainbox-dev/DuAEF_Duik#544]
**Describe the bug**
After successfully rigging the character with the auto-rig function, the head controller doesn't work with zero function. If I use the zero function on the head controller, the head will jump down.

**To Reproduce**
1. Auto-rig the character.
2. Select all my controllers, and use the zero function within Duik Bassel.
3. The problem occurs. The head jumps down.

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
Of course, after zeroing the head controller, the actual position of the head should not change.

**Screenshots**
![bug_report](https://user-images.githubusercontent.com/40012088/67256055-c43c7600-f4b7-11e9-9c2d-fd180d340f13.png)

**System (please complete the following information):**
 - OS: windows 7, windows10
 - Version of After Effects: CC 2018, CC2019
 - Version of Duik: 16.1.3

**Additional context**

**Comment by Nico-Duduf** [comment]
Duplicate #538
Will be fixed in bassel.2
