### ISSUE TITLE
The head structure shift down when add zero to the controller

### ISSUE THREAD

**Issue by Tim1022** [Rainbox-dev/DuAEF_Duik#548]
**Describe the bug**
As the subject, I created a full-body structure and then auto rig it. Everything is fine until I add zero to the controllers, the head structure shift down to the neck's anchor point when I add zero to it.

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19354752/67903022-6b639080-fbcf-11e9-8528-4f19077afee6.png)
before adding zero

![image](https://user-images.githubusercontent.com/19354752/67903034-77e7e900-fbcf-11e9-862c-cb22742b6041.png)

after adding zero

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 16.1.3
 - Version of Duik: 16.1.3

**Additional context**

**Comment by Nico-Duduf** [comment]
duplicate (twice): issues #538 and #544
