### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by Jissse** [Rainbox-dev/DuAEF_Duik#558]
Duik Bassel .2, new null controller fonctions

When ctrl+clicking, it detects if the layer is 3D and makes the controller 3D
But when alt+ctrl+cliking on multiple 3D layers it doesn't detect anything and still creates a 2D controller

Also when ctrl+clicking ona  2D or 3D layer it creates the controller above the selected layer, but with alt+ctrl and multiple layers it still creates it on the top of the timeline

<3

**Comment by Nico-Duduf** [comment]
Ok for 3D Layers

Pour le placement dans la pile de calques, si l'utilisateur sélectionne des calques dispersés on fait quoi ? Au dessus du plus haut ?

**Comment by Jissse** [comment]
Au dessus du plus haut c'est le comportement de motion 2 auquel je suis habitué, ça me paraît logique !

**Comment by Nico-Duduf** [comment]
fixed
