### ISSUE TITLE
Problème en utilisant le rebond

### ISSUE THREAD

**Issue by Gaou30** [Rainbox-dev/DuAEF_Duik#560]
**Describe the bug**
L'effet rebond ne marche pas et me fait un message d'erreur d'expression

**To Reproduce**
1. Créer deux points clés de scale pour faire apparaitre une image .png
2. Cliquer sur "scale" pour selectionner les points clés
3. Cliquer sur "Rebond" de Duik
4. Pas d'effet rebond, et message d'erreur dans les expressions

**Error description, if any**
File: 
Line number: 63-64 
Error message: malheureusement, je ne l'ai pas mémorisé ... mais c'était quelque chose du genre "on ne peut pas appliquer de vitesse ... ... ..., sur un truc non spatial" ... désolé pour le manque de précisions ...

**Expected behavior**
J'espérais que ça fasse comme d'habitude, une apparition en rebond

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: CC19
 - Version of Duik: Duik Bassel.2 v16.2.0

**Additional context**
Je suis repassé à Duik 1.16.1.3, et plus de problèmes !

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, this will be fixed in the next update.
Merci pour l'info, ce sera réparé dans la prochaine update.

In the meantime
En attendant

In the expression, change these lines:

250: `var propSpeed = length(velocityAtTime(t));`
331: `var propSpeed = length(velocity);`
351: `else propSpeed = length(velocityAtTime(t));`

**Comment by Nico-Duduf** [comment]
Note for the fix:
implement this new isSpatial method

```
function isSpatial( prop ) {
  if (typeof prop === 'undefined') prop = thisProperty;
  if (!(prop.value instanceof Array)) return false;
  if (prop.value.length != 2 && prop.length != 3) return false;
  try { sp = prop.speed; return true; }
  catch(e) { return false; }
}
```

**Comment by Nico-Duduf** [comment]
fixed
