### ISSUE TITLE
Probleme fixer la tête DUIK

### ISSUE THREAD

**Issue by lussiana-m** [Rainbox-dev/DuAEF_Duik#566]
Salut à tous ! 

Après avoir rig mon personnage, tout fonctionne correction dans la composition (1), mais dès que je copie colle ma précompostion riggée dans le panel "Projet". Tout fonctionne à nouveau, sauf que la tête n'est plus fixée au cou.

• Étapes 

1. Rig du personnage (Hominoïde)
2. Auto-Rig & IK 
3. Dupliquer la précomposition rig
4. La tête n'est plus fixer au cou, pourtant tout les liens parentés sont identiques, les paramètres aussi

Mauvaise manipulation ? 

J'ai utilisé ce tuto pour repaire et je fais la même manipulation :

[https://youtu.be/i63vPXJ00r0?t=960]

Cela fait aussi déjà plusieurs mois que j'utilise Duik, donc je doute que cela vienne du rig de mon personnage.

 - OS: Mac OS 10.14
 - Version of After Effects: CC 2019
 - Version of Duik: 16.2

Merci d'avance pour votre aide.

**Comment by Nico-Duduf** [comment]
Est ce que les deux compos, après la duplication, ont le même non ?
Si oui le problème vient probablement de là, et je pourrai corriger ça 
dans la mise à jour qui arrive bientôt

**Comment by lussiana-m** [comment]
Quand je duplique, cela donne : [Nom de la composition] 2
Que je rename directement après. 

Merci de ta réponse

**Comment by lussiana-m** [comment]
Pour éviter de recréer un topic, je pose ma 2e question ici : 

Vidéo référence : https://youtu.be/bbd5T6xbRVs?t=1706

Au niveau des connecteurs, quand je créée un 2D slider controller, j'ai maintenant avec la version 16.2, un calque "Connector"  en plus qui s'ajoute (avec les paramètres de mon "2D slider") 

Est-ce normal ? C'est avec la nouvelle version  ? ou la manipulation est toujours la même et je fais une erreur quelque part ?  (cf. screen ci joint) 

<img width="1680" alt="Capture d’écran 2019-11-07 à 17 04 20" src="https://user-images.githubusercontent.com/16304048/68405587-adb54080-0180-11ea-87f1-7de06b4833c3.png">

**Comment by Nico-Duduf** [comment]
C'est normal,
Par contre ici ce n'est pas un forum, mais juste un systeme de bugs reports/feature requests ;)
Le forum est là: https://forum.rainbloxlab.org
