### ISSUE TITLE
AE 2020: Error - internal verification failure (29 :: 0) with Kleaner

### ISSUE THREAD

**Issue by armax9** [Rainbox-dev/DuAEF_Duik#571]
**Describe the bug**
In latest After Effects version I got this bug. 
I have project with using of Kleaner, Spring or Swing effect.

After loading project and opening composition I got that error:
"After Effects error - internal verification failure, sorry! {unexpected match name searched for in group} (29 :: 0)"
and effects not working and not showing in layer. 

Tested with Duik.bassel.2 and Duik.bassel.1 - error still exist. After opening project in AE 2019 - everything works fine.

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: AE 2020
 - Version of Duik: Duik.bassel.2

**Comment by Nico-Duduf** [comment]
I think this is an error with Ae 2020.
Can you try and see what happens in a fresh new project created in 2020 and not 2019, if you have the same error?

**Comment by armax9** [comment]
I created 2 projects in AE 2020 and got that problem. During work everything worked great. I had that issue after next opening

**Comment by Nico-Duduf** [comment]
Can you send me a failing project file please?

**Comment by armax9** [comment]
Ok, here is the example in composition named "bg shapes"
[getid.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3830373/getid.zip)

**Comment by dcturner** [comment]
Also having this issue - errors only appear when re-opening the AEP.

(Although I did see a similar error when I tried to copy / paste keyframes for MasterProperties)
<img width="513" alt="Screenshot 2019-11-27 at 12 32 39" src="https://user-images.githubusercontent.com/881221/69723647-03db2b00-1112-11ea-9285-480457353074.png">

**Comment by Nico-Duduf** [comment]
I don't know what's wrong with this error.

Do you still have the issue with this week update of After Effects, on a fresh project?

**Comment by dcturner** [comment]
I'm not sure this is a DUIK-specific issue. I think it's a general AfterEffects error concerned with MasterProperty keyframes.

Brief explanation - 
I built a rig that contained some exposed properties for DUIK objects - and I noticed some errors when copying / pasting keyframes. Then when I re-opened the AEP, it would display some errors and erase all of my MasterProperty keyframes.

I'll report back if things change, but at present I don't think this is a DUIK-related bug. It was a coincidence that some DUIK properties were involved  👍

**Comment by Nico-Duduf** [comment]
Understood!
I think this may be fixed with the patch released this week for After Effects. You can try this, and if it's still not fixed let me know, I'll warn the Ae team ;)

**Comment by armax9** [comment]
@Nico-Duduf  Latest AE update fixed that for me

**Comment by Nico-Duduf** [comment]
Nice! :)
Thanks for the feedback

**Comment by volfcan** [comment]
I came across with the same issue right after installed a script then when I turned off the script codes on layers It's solved
