### ISSUE TITLE
Wrong  walk cycle behavior after duplicating the whole rig comp

### ISSUE THREAD

**Issue by AaronEcthelion** [Rainbox-dev/DuAEF_Duik#572]
**Describe the bug**
After duplicating the whole rig comp for backup. I  do a procedrual walk cycle in the **duplicated comp**. And the head doesn't rotate properly. Actually I have fonud where the problem is. On the "S | Head" layer(the head structure layer), on the position property, the expression is a little problematic. The 1st line of code, which defines the head ctrlLayer, is using an aboselute path pointing to my original rigged comp. I can manually fix this by modificating the expression. But this would be a step I have to take every time I do a rig. So can you fix this little peoblem? Thx so much!

**To Reproduce**
1. do a full body rig
2. duplicate the rigged comp in the project panel
3. do a procedrual walk cycle in the **_duplicated comp_** and you will find the head behavior is wrong

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
The head layer should rotate properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/40012088/68541769-8eb3ea00-03de-11ea-9ed0-2d6a79f6bb85.png)

**System (please complete the following information):**
 - OS: windows 10
 - Version of After Effects:  2020
 - Version of Duik: 16.2

**Additional context**

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, will be fixed in tomorrow's update

**Comment by Nico-Duduf** [comment]
fixed
