### ISSUE TITLE
Automations "The spring" is not working?

### ISSUE THREAD

**Issue by mamoun86** [Rainbox-dev/DuAEF_Duik#573]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40662938/68543592-b779b680-03c1-11ea-9ea7-3dca048cf55e.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 17.0.0.557 
 - Version of Duik:  16.2.0

**Additional context**

**Comment by Nico-Duduf** [comment]
Yes it is working. What's your issue?

**Comment by mamoun86** [comment]
**Not Working? "The Spring"** 
![image](https://user-images.githubusercontent.com/40662938/68565913-95357680-045d-11ea-9ada-4b2ab77559a9.png)


**worked "Kleaner"**
![image](https://user-images.githubusercontent.com/40662938/68566054-ffe6b200-045d-11ea-852b-ba4f2ac0d1ce.png)


Thanks for answer :)

**Comment by Nico-Duduf** [comment]
So it works. Just play your animation, you'll see by yourself

**Comment by mamoun86** [comment]
Thanks
