### ISSUE TITLE
Error with Spring/Kleaner applied to multiple Layers

### ISSUE THREAD

**Issue by armax9** [Rainbox-dev/DuAEF_Duik#578]
**Issue #1**

After I selecting few layers and using Spring/Kleaner:
1. Expression appears on all layers
2. But Effect "Kleaner" appears only on 1st layer. 
3. AE showing error: "This project contains expression errors"

So Kleaner/Spring working only with 1st layer, and only solution is to copy Effect to other layers.

Attaching video with issue - https://youtu.be/MzfNeYTTQt8

Fixed (Please, only one issue per post):
> **Issue #2**
> 
> Also, I have error from AE with Kleaner/Spring applied to Scale property:
> "Error at line 332 in property 'Scale' of layer 1 in comp. Speed is not supported for non-spatial, multi-dimensional properties - use velocity instead..."
> 
> Video with issue - https://youtu.be/ldPq6Qh70pA
> 
> I understand, that I can use "Separate dimensions" and it works, but it takes time :( Also, it is more comfortable to apply Kleaner/spring just to Scale and not separate dimensions if that isn't needed.
> 
>  - OS:  Win 10 1909
>  - Version of After Effects: 2019/2020
>  - Version of Duik: 16.2

**Comment by Nico-Duduf** [comment]
the second issue is fixed with duik 16.2.1

**Comment by Nico-Duduf** [comment]
fixed
