### ISSUE TITLE
Connector

### ISSUE THREAD

**Issue by SEGA201** [Rainbox-dev/DuAEF_Duik#579]
**Describe the bug**
Trying to connect keys to a rotation of a structure through connector:
at first it gets some excess symbols (see in screenshot)
and at second when connecting keys to property it creates a controller "C | Connector" in compostion
In any case, it still works, but these two points do not appear in version v16.0.9, which I still have to use to avoid some troubles

**To Reproduce**
1. create some keys (in a layer parented to a structure)
2. choose rotation in structure through "select a master property"
3. select previous keys and click on a "Connect to properties"

**Expected behavior**
excess symbols didn't appear and controller "C | Connector" isn't created

**Screenshots**
![1](https://user-images.githubusercontent.com/56382023/68768970-97056280-0634-11ea-892f-e9c2fea7a4f5.PNG)

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: CC18
 - Version of Duik: v16.2.1

**Comment by Nico-Duduf** [comment]
The symbols should be the ° character, I don't know why it does not appear correctly on your Duik... I'd have to investigate.

The new controller is perfectly normal, it's a way to gather all connector parameters, which is better both for the user and for Duik, it makes it more stable.
