### ISSUE TITLE
Multiple DUIK toolbars 

### ISSUE THREAD

**Issue by Protozoan-248** [Rainbox-dev/DuAEF_Duik#584]
Hi there,

DUIK is full of tools and to get the right one requres sometimes a few clicks. It would be nice to have **an option to open multiple DUIK "instances**". This offers KBar 2 and it is awesome.

Thank you.

**Comment by Nico-Duduf** [comment]
There's already the optionnal panels, it's not enough?

BTW, you can also just duplicate the script file to have other full instances.
