### ISSUE TITLE
Scrolling of the DUIK toolbar

### ISSUE THREAD

**Issue by Protozoan-248** [Rainbox-dev/DuAEF_Duik#585]
Hi there,

DUIK is full of awesome tool but to get all of them the palette is pretty tall. It would be nice to be **scroll friendly**. Like the Motion 3 extension.

And in addition the icons could scale down when the "window" gets smaller.

Thank you

**Comment by Nico-Duduf** [comment]
Unfortunately this is not possible for a script lile Duik, only extensions can do that.
