### ISSUE TITLE
auto upgrader

### ISSUE THREAD

**Issue by DoronT770** [Rainbox-dev/DuAEF_Duik#586]
thank you for your very quick respond.
dont know if its easy or not, but maybe an auto update could be nice?
it wasnt so needed like now when every other day a new Version comes out

**Comment by Nico-Duduf** [comment]
I'm working on it. It's more difficult than it seems as Duik has to replace itself, and may be in a folder which needs administrator privileges...

**Comment by Nico-Duduf** [comment]
Duplicate: Issue #87
Which will be updated soon
