### ISSUE TITLE
Bug: Odd behavior with Kleaner and AE2020 bug?

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#588]
**Describe the bug**
Using the Kleaner on a simple animation along an animation path with auto orient along path activated makes it perform a weird rotational glitch at the end. Is there an AE bug involved? Shape layer is distorted when auto oriented (but also pixel layers after additional tests)

**To Reproduce**
1. Create position animation
2. Convert animation path to Bezièr Path 
3. Auto Orient layer
4. Klick Kleaner

**System (please complete the following information):**
 - OS: 10.14.6
 - Version of After Effects: 2020 (17.0.0)
 - Version of Duik: 16.2.2

![kleaner](https://user-images.githubusercontent.com/38455050/69485339-4f55b680-0e3e-11ea-9f37-4b086c015805.gif)

[Kleaner.aep.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3882940/Kleaner.aep.zip)

**Comment by Nico-Duduf** [comment]
This one is weird!
Thanks for the feedback, I'll have a look ASAP

**Comment by reneandritsch** [comment]
Nicolas, don’t mind the distortion because I accidentally created a non square comp which distorts the object but the movement is still happening in this weird way. At the end objects turn in a weird way. When having the anticipation active, why does the object not follow the animation path in the beginning? Thanks René

See here …

![move](https://user-images.githubusercontent.com/38455050/69494732-4ce77100-0ebf-11ea-9bf1-db75d5164f16.gif)

**Comment by Nico-Duduf** [comment]
I've fixed the issue for the rotation (and improved the performance a little bit), it will be in the next update. You may have to raise the 'precision' option to avoid these jumps.

The object not following the trajectory with the anticipation is normal, move the keyframes a bit later in the timeline to actually see the whole anticipation, you'll understand ;)

**Comment by reneandritsch** [comment]
Thank you, Nicolas!
