### ISSUE TITLE
Rig breaks when removing a comp containing controllers extracted with master props

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#589]
**Describe the bug**
See http://forum.rainboxlab.org/posting.php?mode=reply&f=11&t=1041

**Comment by pralidoximechloride** [comment]
[duik_test.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3883567/duik_test.zip)

I used my rig in 3 different comps and I decided that I dont need one of them anymore. When I delete the master comp I dont need, my rig got broken. Is it logical? How to remove unwanted comps to keep your project cleaner? Thank you.

**Comment by Nico-Duduf** [comment]
The rig you're removing has probably been extracted with expressions instead of master properties.
With Duik 16.2.1 there was an issue where the settig to extract using MPs was not kept between sessions, this has been fixed in 16.2.2, sorry for that
