### ISSUE TITLE
Leg-FK not working with Essential Graphics Panel

### ISSUE THREAD

**Issue by German-Maui** [Rainbox-dev/DuAEF_Duik#590]
Hey,
I guess I found a bug with using DUIK via the Essential Graphics Panel. When I try to animate the FK parameters of the leg(not sure if it is the same for arms/spine ect.) it doesn't transfer over to the "pre-Comp"- If I change the settings without keyframes it works fine but as soon as I set some keyframes it doesn't do anything. Ik on the other side seems to work and also if I set keyframes in the pre-comp for the FK-paramters it works fine.
I have made a simple AFX project to show you what I mean, which you can get from this link:
https://adobe.ly/34kKFzV

I'm using AFX 2020 on a win10 machine and the latest DUIK Version 16.2

Best
Pascal

**Comment by mamoun86** [comment]
[https://assets.adobe.com/id/urn:aaid:sc:AP:0c9a2efe-0a50-402c-ba86-d6d5dae76356?view=file](url)

**Comment by mamoun86** [comment]
[DUIK_Feet_EG_BUG to Good.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3886724/DUIK_Feet_EG_BUG.to.Good.zip)

**Comment by mamoun86** [comment]
[DUIK_Feet_EG_BUG to Good.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3886815/DUIK_Feet_EG_BUG.to.Good.zip)

good? no?

**Comment by German-Maui** [comment]
Yeah this seems to work fine. Was it a Bug or did you change something else?

**Comment by Nico-Duduf** [comment]
This is a known bug in Ae2020,
you have to add a keyframe on the corresponding master property so the animation works.
The latest version of Duik (16.2.2) does that automatically, waiting for the Ae team to release a patch fixing this
