### ISSUE TITLE
Kleaner expression bug on 3D layer with ExtendScript motor

### ISSUE THREAD

**Issue by AurelienDelamare** [Rainbox-dev/DuAEF_Duik#595]
**Describe the bug**
After Effect return that "length" in "property" doesn't exist.
In isSpatial function :
`	if (prop.value.length != 2 && prop.length != 3) return false;`

**To Reproduce**
Add Kleaner on any property on 3D layer with ExtendScript motor

**Comment by Nico-Duduf** [comment]
thanks

you can fix it by replacing the line by this:
`if (prop.value.length != 2 && prop.value.length != 3) return false;`

I'll fix it in the next update

**Comment by Nico-Duduf** [comment]
fixed
