### ISSUE TITLE
Kleaner slower than the old spring

### ISSUE THREAD

**Issue by onebrightdot** [Rainbox-dev/DuAEF_Duik#601]
**Describe the bug**
The additions to the Spring automation have made it too slow for practical use. Is there anyway to use it in legacy mode?

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 
 - Version of Duik: 

**Additional context**

**Comment by Nico-Duduf** [comment]
Really?
It should be faster actually...
Do you have any comparison at hand, or could you make one, importing a composition where the old version is used, in a project where you'd do it again with the new one, using the same layers and setup?

**Comment by Nico-Duduf** [comment]
If anyone noticing this performance issue could prepare a project for comparison, that would be great. Thanks

**Comment by Nico-Duduf** [comment]
I believe this is the same request as #649
Closing issue.
