### ISSUE TITLE
Positioning with Spring effect does not play smooth/adding effects to multiple layers doesn't work

### ISSUE THREAD

**Issue by FoxhoundGTI** [Rainbox-dev/DuAEF_Duik#605]
**Describe the bug**
When using "Spring" effect on position keyframes, the object stops then continues the animation, you can clearly see a jump in movement, where the movement stops completely then jumps into the spring motion. (daily use)

Furthermore, when selecting multiple keyframes to add spring effect, it does not work, you can only select one keyframe per layer so duik can add the effect. 

**To Reproduce**
1. add two object to after effects, add position keyframes going from one side to the other. 
2. select both layers keyframes for the end position, add "spring effect" only one layer will take the effect
3. play animation. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
animation should continue and play smooth spring effect just like previous versions. Duik should be able to select multiple keyframes from multiple layers and add the effect. 

**Screenshots**

**System (please complete the following information):**
 - OS: Mac OS Mojave
 - Version of After Effects:  16.1.3
 - Version of Duik: 16.2.1

**Additional context**

**Comment by Nico-Duduf** [comment]
fixed
