### ISSUE TITLE
Bug in translate file (maybe?)

### ISSUE THREAD

**Issue by CheccoCasty** [Rainbox-dev/DuAEF_Duik#612]
**Describe the bug**
Hi, 
everytime i open after effects (while duik bassel is docked) or every time i open the tab, it presents me this error (attached). 
i had to uninstall toolkit because it opened with debubbing everytime cousing ae crash, but the code line was apparently inherent to the translate files.

 - OS: Windows 10 (updated)
 - Version of After Effects: cc2019 (updated)
 - Version of Duik: 16.2.2

![Screenshot_1](https://user-images.githubusercontent.com/58597138/70326259-6334eb80-1834-11ea-8c59-82894023d62a.png)

**Comment by Nico-Duduf** [comment]
Duplicate: #581
