### ISSUE TITLE
Automatically fill Dropdown Menue fx with layers

### ISSUE THREAD

**Issue by German-Maui** [Rainbox-dev/DuAEF_Duik#613]
Hey,
with the latest version of AFX I started using the Dropdown Menu Expression CTRl in combination with Master Properties quite a lot. I used for Blinking Animations or to circle between layers/logos which is super useful.
The expressions are not complex nor is it hard to set it up but I think this would be a good task for a script as it is a pretty repetetive task.

I could imagine it to work like follows:
You have several layers in your comp and when you hit the button in the script it pops up a dialogue where we can enter the Name of the Dropdown Menu followed by another dialogue to enter the Names of the entries in the list but it would be nice if we could bypass this and the script fills the slots with the layer names.
In addition it adds the Dropdown Menu to the Essential Graphics Panel so that it is possible to use it directly in another comp.

Maybe someone can come up with even more features ;-)

**Comment by Nico-Duduf** [comment]
Unfortunately it is not possible to change the content of these controls via scripting in Ae (yet)...
