### ISSUE TITLE
Cléttoyeur Duik Bassel 2

### ISSUE THREAD

**Issue by Magraph** [Rainbox-dev/DuAEF_Duik#614]
**Describe the bug**
Cléttoyeur Duik Bassel 2 ne se lance pas.

**To Reproduce**
1. Reproduction pas à pas de la manipulation de la 11è à la 12è minute de https://www.youtube.com/watch?v=mA7-oO4KwZw
2. L'effet marionnette reste seul, l'effet cléttoyeur ne s'ajoute pas à la liste.
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: W10
 - Version of After Effects: CC2020
 - Version of Duik: 16.2.1

**Additional context**

**Comment by Nico-Duduf** [comment]
Il faut bien sélectionner les valeurs, les positions des coins dans la timeline (ou les images clefs), c'est le cas ?

**Comment by Magraph** [comment]
Bonjour,
Désolée, je n'avais pas saisi ce détail dans la démonstration. Effectivement en sélectionnant les clés des coins de marionnette ça marche, cet effet est super cool !!!Un grand merci !
Magali Le Dissez
    Le mercredi 11 décembre 2019 à 11:09:07 UTC+1, Nicolas Dufresne <notifications@github.com> a écrit :  
 
 
Il faut bien sélectionner les valeurs, les positions des coins dans la timeline (ou les images clefs), c'est le cas ?
