### ISSUE TITLE
Instead of master property to 2d controller, it creates new one that looks like a symbol of controllers

### ISSUE THREAD

**Issue by Libba** [Rainbox-dev/DuAEF_Duik#615]
**Describe the bug**
Instead of master property to 2d controller, it creates new one that looks like a symbol of controllers.

**To Reproduce**
1) Create a circle - head in .ai file
2) Set three positions >one base, one slightly to left and one slightly to right (mad with shift + arrow)
3) select head layer and create a 2D Controller (contents: C | head and CGB | head)
4) select all positions
5) connect to properties
6) connector symbol appears (called C | Connector)
7) it have all Effects (# 2D value), so I have to copy them to C | head layer, and change code from C | Connector to C | head in expression of position of head layer.

**Error description, if any**
All in screen shots
1) when C | Connector layer is deleted without copying the Effects
2) when I change C | Connector to C | head after C | Connector layer is deleted without copying the Effects

**Expected behavior**
C | Connector should not apper, but it should link head to C | head. No symbols appearing.

**Screenshots**
https://imgur.com/a/0dPnzVq

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects:  2020 17.01
 - Version of Duik:  16.2.2

**Additional context**
The thing is I have to fix it:
1) Copy Effect (# 2D Value) from **C | Connector** symbol
2) Place it on C | head Effects
3) Delete **C | Connector** layer (yes, that one with symbol)
4) Go to code and repace all **new C | Connector** with the C | head

all is working then, but I don'twant the symbol to appear.

If the original name of C | head is C | Connector, it will create C | Connector 2 layer with symbol.

Also, I can't make Y axis work, cause it is pasting on the X effect, even if I change the name.

**Comment by Nico-Duduf** [comment]
This is how it works.
Read this https://duik-docs.rainboxlab.org/connector.html
