### ISSUE TITLE
Spring (Kleaner) not working when turning a layer to 3d

### ISSUE THREAD

**Issue by ricciofix** [Rainbox-dev/DuAEF_Duik#618]
**Describe the bug**
Spring automation now known as Kleaner stops working on scale property (actually also on position and probably on all other properties) as soon as you switch the layer to be 3d, I don't remember this to be a problem in the previous versions.

**To Reproduce**
1. turn a layer to 3d
2. animate scale or position (and probably other properties)
3. add spring, the spring effect stops and you get an error at line 109

**Error description, if any**
File: 
Line number: 109
Error message: cannot copy the message, you only see the message when you click on the code (maybe change it) screenshots available

**Expected behavior**
The layer should continue to spring as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/7247667/70713276-8ac8ff80-1cdd-11ea-9b9e-846a3f27b1f3.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 16.1.3
 - Version of Duik: Duik Bassel 2

**Additional context**

**Comment by Nico-Duduf** [comment]
fixed
