### ISSUE TITLE
cannot duplicate

### ISSUE THREAD

**Issue by gogosamlee** [Rainbox-dev/DuAEF_Duik#621]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nico-Duduf** [comment]
What are we supposed to understand with this issue?

**Comment by gogosamlee** [comment]
Hi,
Sorry to trouble you. I did managed to solve my problem. Thanks 


Sam Lee
Gogosam Design Consultant
Mobile: 96334445
email: gogosam@me.com
 
Disclaimer: This email is confidential and intended solely for the use of the intended addressee. 
If you have received this email in error, please notify the sender and delete this email immediately 
and you should not disseminate, distribute or copy this e-mail. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any action in reliance on the contents 
of this information is strictly prohibited.  Any views expressed in this email are solely those of the author
and do not necessarily represent those of Gogosam’will not accept any liability in respect of communication 
which are contrary to Gogosam’s business and policy.
