### ISSUE TITLE
lissage sur rebond

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#622]
Il y a un lissage étrange sur les rebonds du clettoyeur,
c'est flagrant quand on augmente le damping :

![01](https://user-images.githubusercontent.com/25553786/71347974-d2684a80-256b-11ea-8ff6-67b45b08fa25.png)
![02](https://user-images.githubusercontent.com/25553786/71347976-d2684a80-256b-11ea-8a6c-5f88400c2648.png)

[test clettoyeur lissage.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/3994307/test.clettoyeur.lissage.zip)

**Comment by Nico-Duduf** [comment]
![image](https://user-images.githubusercontent.com/8526542/71741557-7d77de80-2e5f-11ea-93e5-270f2b626aea.png)


ET BIIIIM!
