### ISSUE TITLE
Duplicates Bug

### ISSUE THREAD

**Issue by cerealmilkmedia** [Rainbox-dev/DuAEF_Duik#623]
**Describe the bug**

**To Reproduce**
1. Create a custom 1 element structure
2. Select structure and end and duplicate with duik
3. Two new structures are created connected to original structures end

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 
 - Version of Duik: 

**Additional context**

**Comment by Nico-Duduf** [comment]
fixed
