### ISSUE TITLE
Head and Neck switched.

### ISSUE THREAD

**Issue by Exadus04** [Rainbox-dev/DuAEF_Duik#627]
Im reporting that Ive been running into a bug that mixes up the head and neck structures when creating a spine structure.

Thanks.

**Comment by Exadus04** [comment]
Not sure why when creating a spine structure with selected layers that the order is being reversed.

**Comment by Nico-Duduf** [comment]
When layers are selected, Structures are created on the location of their anchor points, maybe that's your issue?

Could you post a screenshot or something to give more details about the issue? Thanks!
