### ISSUE TITLE
DUIK UI Scrip After Effects does not work ... 

### ISSUE THREAD

**Issue by barrubinstein** [Rainbox-dev/DuAEF_Duik#628]
**Describe the bug**

**To Reproduce**
1. Uninstall and reisintall Duik both times
2. Install the latest version 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
The Animation and the Setup never work. Or they are empty, or if there are all the effects, it won't apply on any layers... It does this only since I updated my Adobe 2019 after Effects to the 20202 version...

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 2020
 - Version of Duik: Duik Bassel 2

**Additional context**

**Comment by Nico-Duduf** [comment]
I don't understand what the issue actually is.
Could you add more details, or maybe attach a screenshot to show what's wrong?

**Comment by Nico-Duduf** [comment]
No news, closing issue.
