### ISSUE TITLE
Unlinked Extracted Controllers with the MP Method

### ISSUE THREAD

**Issue by ronruizG** [Rainbox-dev/DuAEF_Duik#631]
**Describe the bug**
Extracted controls are working but they are not linked to each other so when you rotate a parent control (i.e. body control) the child control (i.e. head Control) doesn't follow, if you rotate the now offsetted child control (head Control) it rotates the controlled shape, this can be really confusing.

**To Reproduce**
1. Extract controls with the MP method
2. rotate a Parent Control (Body control

**Expected behavior**
Child Controls should follow so you can still look at them in the context of the movement

**System (please complete the following information):**
 - OS: Win 10
 - Version of After Effects: CC 2020
 - Version of Duik: 2 (v16.2.4)

**Comment by ronruizG** [comment]
Ok an update to this problem. The problem shows up only if the controllers in the rig comp were Zero out with the "Zero" tool, as this creates some nulls as Aux Layers and now those nulls control the hierarchie of the Rig it seems that this confuses the "Extract" don't know if this could be fixed but It would be nice.

**Comment by Nico-Duduf** [comment]
Thanks for the details. I think it can be fixed, I'll have a look at that ASAP, which may be in a week or two

**Comment by Nico-Duduf** [comment]
It's in the roadmap for the 16.2.5 version with a few other bugfixes

**Comment by Nico-Duduf** [comment]
Fixed, available in a few days
