### ISSUE TITLE
Extract Controllers is not working ?

### ISSUE THREAD

**Issue by mamoun86** [Rainbox-dev/DuAEF_Duik#635]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number: 5685
Error message: 

**Expected behavior**

**Screenshots**

![unknown](https://user-images.githubusercontent.com/40662938/73824075-33896c00-4802-11ea-9d0a-eaa671afe72c.png)

**System (please complete the following information):**
 - OS: windows 10
 - Version of After Effects: 17.0.2
 - Version of Duik: 16.2.5

**Additional context**

**Comment by Nico-Duduf** [comment]
can you send me the aep file where you have this issue so I can check what's going on?

**Comment by mamoun86** [comment]
[Extract Controllers.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/4161570/Extract.Controllers.zip)

**Comment by Nico-Duduf** [comment]
Thanks, I think it's fixed with 16.2.6 I've just published.
