### ISSUE TITLE
Duik blink automation throws error on making the frequency value as 0

### ISSUE THREAD

**Issue by lucifer0297** [Rainbox-dev/DuAEF_Duik#640]
**Describe the bug**
When the Blink automation under Duik Automations is applied to a property, it throws an error when the frequency is made 0 as no mathematical calculation cannot be applied with the number 0.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create any shape layer
2. Add Duik Blink to any property, for eg. opacity of the layer
3. When the frequency value is set to 0, it gives an error

**Expected behaviour**
When I set the frequency to 0, I expect the property to stop blinking and give retain the original value of it. For example, if I set the blink to opacity, I expect the layer to retain the original opacity (say 100%) when I make the frequency as 0.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - The version of After Effects: After Effects 2020 (17.0.2)
 - The version of Duik: 16.2.5

**Additional context**
I would usually get around the problem by choosing the larger of the two set values (say 100 in case of opacity) if the frequency is set to 0. Here's the sample code I use:

//Duik.blink
var fx = effect("Opacity Blink")
var phase = fx(3).value;
var timeOn = fx(4).value;
var offset = fx(5).value;
var valueA = fx(1).value;
var valueB = fx(2).value;
if(phase != 0){
freq= timeToFrames(1)/phase;
var currentFrame = timeToFrames(time+offset/phase/100);
if (currentFrame%freq > freq*timeOn/100) valueB;
else valueA;}
else{
	if(valueA>valueB) valueA;
	else valueB;
}

**Edit**
Another better solution could be to use the original property value if the frequency is made 0. Thus,

//Duik.blink
var fx = effect("Opacity Blink")
var phase = fx(3).value;
var timeOn = fx(4).value;
var offset = fx(5).value;
var valueA = fx(1).value;
var valueB = fx(2).value;
if(phase != 0){
freq= timeToFrames(1)/phase;
var currentFrame = timeToFrames(time+offset/phase/100);
if (currentFrame%freq > freq*timeOn/100) valueB;
else valueA;}
else{
	transform.opacity;
}

**Comment by Nico-Duduf** [comment]
fixed,
thanks for the feedback, will be available very soon in 16.2.7
