### ISSUE TITLE
Rigging Bug

### ISSUE THREAD

**Issue by skyes379** [Rainbox-dev/DuAEF_Duik#643]
**Describe the bug**
Whenever I try to auto-rig an arm (but the option for hooves) it creates a composition ou of the "magic is happening" loading screen. This makes the icon for magic is happening editable and ends up not auto-rigging the front leg of my animation. 

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: ~/AppData/Roaming/Adobe/After%20Effects/17.0/Scripts/ScriptUI%20Panels/Duik%20Bassel.2.jsx
Line number: 5270
Error message: 
Undefined is not an object
**Expected behavior**
Just want to auto-rig a front leg of a cow so that I can animate it.

**Screenshots**

**System (please complete the following information):**
 - OS:  64 bit operating system
 - Version of After Effects: 17.0.2
 - Version of Duik: Duik Bassel.2 v16.2.6 

**Additional context**

**Comment by Nico-Duduf** [comment]
I've found the bug in Duik, it's fixed for the next update with a few other issues.

**Comment by Nico-Duduf** [comment]
duplicate: #642

**Comment by skyes379** [comment]
Thank You, may I ask when this update will be?*

**Comment by Nico-Duduf** [comment]
It should take less than a week, but I don't know exactly, I have still one last issue to fix which is a bit complicated, and don't have much time to spend on it these days.

13 feb. 2020 8:48:15 a. m. skyes379 <notifications@github.com>:
