### ISSUE TITLE
Extract controllers seems broken - v16.2.7

### ISSUE THREAD

**Issue by LarsJandel** [Rainbox-dev/DuAEF_Duik#648]
**Describe the bug**
v16.2.7 - Win 10 - AE 2020
Using "extract all the controllers from the precomposition" doesn' t finish, unfortunately. Using master properties within AE 2020. It stops after the first controller, the hand. I rolled back to v16.2.6 and it works as expected.

**To Reproduce**
1. drop the precomp with structures and controllers into a new comp
2. click "extract all the controllers from the precomposition"

**Error description, if any**
No error.

**Expected behavior**
Finish extracting all controllers.

**Screenshots**
-

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 2020 [17.0.0 build 557]
 - Version of Duik: 16.2.7

**Additional context**
Works as expected in the previous version v16.2.6
Thanks Duduf!

**Comment by Nico-Duduf** [comment]
wooops... Thanks for the feedback I'll have a look at that ASAP

**Comment by Nico-Duduf** [comment]
Hi again, I can't reproduce, here it seems to work correctly. Could you send me a failing project so I can have a look?
Thanks!

**Comment by LarsJandel** [comment]
Seems project file unrelated:
Tested with 16.2.7 and a clean project again with the same behavior.
- created a comp
- created a hominoid
- selected all layers → Auto-Rig & IK
- dropping that comp in an empty one
- extract controllers via master properties
→ stops creating the necessary master properties after the first controller = hand
   - the controllers do get extracted, but the links / master properties do not finish, so the rig doesn't work

- extraction via expressions works fine though

unfinished master properties creation / linking the rig properly:
![unfinishedMasterPropertiesExtraction](https://user-images.githubusercontent.com/32457827/75283431-29f89000-5813-11ea-96e3-62d9050f0e4d.png)

**Comment by LarsJandel** [comment]
If you still prefer to look at a project: This is pure Duik, no artwork. The guide flag is removed from the structures, so they are visible in the animation comp. The project contains extraction `test`s via v1.2.6 and v1.2.7 using master properties and `try yourself` comps, so you can try extracting the controllers yourself. Again, in v1.2.7, the creation of the master properties stops after the 1st controller (Hand 2), while it works in v1.2.6 just fine.
Project screenshot:
![Duik_-_v127_-_MP_extract_issue](https://user-images.githubusercontent.com/32457827/75312872-8a132480-585b-11ea-8404-2a96505ee17d.png)
Project file:
[Duik_-_v127_-_MP_extract_issue.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/4253449/Duik_-_v127_-_MP_extract_issue.zip)
Thanks!

**Comment by Nico-Duduf** [comment]
Sooo that's very strange, I can confirm it works here....
Same tests, and using your project too.

We have to find the difference between you and me.
I tried on Ae 17.0.2 (which is not the latest one, I'm updating right now to test again), and it's in English. I'm going to test with Ae in French too.

**Comment by Nico-Duduf** [comment]
Can you test with javascript debugging enabled, and/or Dev & Debug mode in Duik (in the settings panel) and post any error which may be shown?

**Comment by Nico-Duduf** [comment]
Oh I did not wee you stated you were on Ae 17.0.0
Maybe something was fixed since then, could you update and try again? (Or I'll see if I can revert to it on my side)

**Comment by LarsJandel** [comment]
Oh well... ...all good now - thanks for the hint!

I wasn't really paying attention to AE's version number and as the Creative Cloud app didn't show an update, even when doing the manual "Check for updates", I thought I was using the latest version. But yeah, the dot number didn't match the latest release. 
So uninstalling 17.0.0 was the only way to install/update to 17.0.4 and - now Duik v16.2.7 works just fine! 🤘
Sorry for the trouble. Don't know, what's the issue with AE 17.0.0. though. I guess you can just keep a note regarding this possible issue with that version of AE and Duik or install that version yourself to investigate if you are bored. Which you are definitely not. 🙃

Thanks again for taking the time Duduf!
