### ISSUE TITLE
walk cycle

### ISSUE THREAD

**Issue by Kytin** [Rainbox-dev/DuAEF_Duik#651]
**Describe the bug**

**To Reproduce**
1. 
![Annotation 2020-02-25 172944](https://user-images.githubusercontent.com/61531303/75412512-47e3f480-58e8-11ea-8b4c-057ddd2679c9.png)
![Annotation 2020-02-26 2234493](https://user-images.githubusercontent.com/61531303/75412527-53cfb680-58e8-11ea-9df7-99d4e85c9210.png)

2.  as you can see the legs stretch out during walk cycle how do i stop that? it looks like its doing ballet
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 
 - Version of Duik: 

**Additional context**

**Comment by Nico-Duduf** [comment]
Please, do not use bug reports for getting support. Thanks.
