### ISSUE TITLE
Link and constrains don't work

### ISSUE THREAD

**Issue by BlackEyeDCat47** [Rainbox-dev/DuAEF_Duik#652]
**Describe the bug**
Link and constrains Tab don't react on clicking. 

**To Reproduce**
1. Launch Duik
2. Open Rigging Tab
3. Click on Links and Constrains

**Expected behavior**
A new tab should appear

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 16.0.1
 - Version of Duik: 16.2.7

**Comment by Nico-Duduf** [comment]
Can you update After Effects (even if you keep 16.x, this is not the latest patch) and try again?
If it still does not work, enable javascrit debugging and the "dev & debug" mode in Duik, and post here the error which should be shown.
Thanks

**Comment by BlackEyeDCat47** [comment]
Thank you for your reply.  My decision was instead of installing it, just
open Duik by Run Script File option.
After doing this, it works perfectly fine. I will try your advice after i
will finish my project, just to not mess up with it.
Thank you!

сб, 29 февр. 2020 г. в 20:34, Nicolas Dufresne <notifications@github.com>:
