### ISSUE TITLE
Auto-Parent: Can't re-parent to another layer

### ISSUE THREAD

**Issue by LarsJandel** [Rainbox-dev/DuAEF_Duik#653]
**Describe the bug**
When using the `Auto-Parent` button to _parent layers to the last selected one_, I can't re-parent an already parented layer/layers to a new/other layer.

**To Reproduce**
1. parent a layer to another layer
2. select the child and select a different layer to parent to
3. click the `Auto-Parent` button

**Expected behavior**
I should be able to parent an already parented layer to a new parent via the `Auto-Parent` button.

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 17.0.4 - Build 59
 - Version of Duik: 16.2.7

**Additional context**
Btw, the help pop-up for `Auto-Parent` displays the info regarding the _Parent Constraint_. 😉

Thanks Duduf!

**Comment by Nico-Duduf** [comment]
hum actually I did that to make it quicker to parent all unparented layers to a specific one. But it should be as you describe by default, and my way as an option, I'm doing this.
Will be fixed in the update today ;)

**Comment by Nico-Duduf** [comment]
Done
Click: parent all layers to the last selected one
Alt-Click: parent orphans to the last selected one
