### ISSUE TITLE
Minor bug in "Bake Appearance" button in the Edit Bones panel

### ISSUE THREAD

**Issue by Webscribe** [Rainbox-dev/DuAEF_Duik#655]
**Describe the bug**
When baking the appearance of a tangent layer in the bones created by DUIK, it doesn't delete the expression in the stroke width field, but it does delete the Effect: "Bone" which the stroke width references. This creates in error. No error is cause if you just bake the vector point bones.

**To Reproduce**
1. After creating bones on a shape, select a tangent bone. 
2. Press the "Bake Appearance" button tin the Edit Bones Panel.
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
I assume the script should be deleted from the "Stroke Width" field. If I manually delete the script the error goes away.

**Screenshots**
<img width="1028" alt="Screen Shot 2020-03-10 at 11 38 51 AM" src="https://user-images.githubusercontent.com/40582233/76347399-cb77eb00-62c3-11ea-8e40-65f8474ffb33.png">

**System (please complete the following information):**
 - OS: MacOS q0.14.6
 - Version of After Effects: 17.0.4 
 - Version of Duik: 16.2.7

**Additional context**

**Comment by Nico-Duduf** [comment]
Thanks for the feedback, will be fixed very soon in 16.2.8

**Comment by Nico-Duduf** [comment]
done
