### ISSUE TITLE
Auto-Rig Neck & Head broken link

### ISSUE THREAD

**Issue by iTerentius** [Rainbox-dev/DuAEF_Duik#662]
**Describe the bug**
I've just started using Duik again after a few years so coming in fresh to the new versions. I'm using AE 2020 17.0.5 (build 16) and Duik 16.2.9. When creating a homonid structure and applying auto-rig, the head bone is detached. When I move the Hip controller up and down, the entire kinetics work, but the head stays in place. 

**To Reproduce**
1. Create Homonid
2. Select all of the #S layers
3. auto-rig

**Expected behavior**
I believe the head should move with with the rest of the spine when you move the Hip controller. Instead it stays in place and the neck and head separate.

**System (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Version of After Effects: 2020 17.0.5 (build 16) - but also in 2019 when I tried.
 - Version of Duik: 16.2.9

**Additional context**
At first I thought it was after moving the bones in place with my art or parenting art to the bones. But I was able to reproduce with not art, just the Duik homonid.

I've also asked about this on Jake Bartlett's skillshare course. He said I wasn't the only one with the issue.

**Comment by Nico-Duduf** [comment]
Thanks for the feedback. I'll have to test but I think what you want is the behavior of the "Body" controller instead of the "hips" controller. _Hips_ is meant to move only the hips, while _Body_ is meant to move hips+torso+neck+head. Which makes hips very useful to adjust the pose without the head moving, it's by design.

**Comment by iTerentius** [comment]
Ah! Okay. Well, then likely not a bug at all. I was worried about this which was also I checked with others, but this totally makes sense. Thanks.
