### ISSUE TITLE
Bug wheel quand le layer est parenté à un calque à echelle négative

### ISSUE THREAD

**Issue by AurelienDelamare** [Rainbox-dev/DuAEF_Duik#664]
**Describe the bug**
L'expression ne s'applique pas sur la rotation si le calque est parenté à un calque avec une échelle négative. Fait planter Duik si le déboggage JS est activé.

**To Reproduce**
1. Deux calques, un est enfant de l'autre.
2. Le calque parent reçoit un scale négatif sur x
3. On applique le wheel sur l'enfant

**Screenshots**
https://i.ibb.co/gvGjCDT/Capture.jpg

**System (please complete the following information):**
 - OS: Win 10
 - Version of After Effects: 17.0.5
 - Version of Duik: 16.2.9

**Comment by Nico-Duduf** [comment]
fixed

**Comment by Nico-Duduf** [comment]
merci pour le feedback
