### ISSUE TITLE
2D Camera act weird when animating "Truck In/Out"

### ISSUE THREAD

**Issue by SamuelTell** [Rainbox-dev/DuAEF_Duik#665]
**Describe the bug**
The position of the "2D Camera Controller" doesn't stay in the correct place after we animate the "Truck In/Out". In my example, I put a keyframe for "2D Camera Controller" (0,0), and Truck (0%)  at 1 second. Go back in timeline and put another keyframes on "2D Camera Controller" (-50,-50), and Truck (-50%). When go back to the first keyframe at 1 second... the "2D Camera controller" in not in the correct place, it is at -50,-50.

**To Reproduce**
1. Click in "2D Camera" on Duik;
2. In timeline put the needle of the timeline at the middle of the timeline;
3. Select "2D Camera Controlelr" layer and press "P";
4. Click in the clockwatch for the position, to create a keyframe at 0,0;
5. In the "Effect Controller" click in the clockwatch for "Truck In/Out" to create a keyframe for 0%;
6. Press "U" to show all the keyframes;
7. Put the needle of the timeline at the beginning of the timeline, 
8. Create new keyframes for the two properties (position and truck), either moving the Null Object in Viewport or draging the x/y value in timeline (-50,-50) , and change the value of Truck to -50%;
9. Go back to the first keyframes we put in timeline that susposed to be 0,0 for the position of the Null but its not! Its -50,-50!

**System (please complete the following information):**
 - OS: Win 10 Pro
 - Version of After Effects: 17.0.6
 - Version of Duik: 16.2.10

I can record a video if necessary.

**Comment by Nico-Duduf** [comment]
Thanks for your feedback, I'll have a look at that ASAP

**Comment by Nico-Duduf** [comment]
Fixed, available in 16.2.11 very soon!
