### ISSUE TITLE
Set Ease and Velocity button not working

### ISSUE THREAD

**Issue by SeanDavid740** [Rainbox-dev/DuAEF_Duik#667]
**Describe the bug**
When using the "Set Ease and Velocity on Selected Keys" button under Animation, the button does not apply the changes (reflected as preset in DUIk panel) to selected keyframes on timeline.

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 10.12.6
 - Version of After Effects: 2019
 - Version of Duik: Bassel.2

**Additional context**

**Comment by Nico-Duduf** [comment]
Thanks for your feedback, I'll fix that in the next update if I can repro

Can you give me the exact version of Duik (16.2.?) and After Effects (16.?.?).
Have you/can you try on Ae 2020 too please?

Thanks

**Comment by SeanDavid740** [comment]
Thank you for th response. I realized I was not using the latest update of
16.2.10. After updating, the global easing button seems to be working fine.
Thanks again.

Regards,
Sean Platt
