### ISSUE TITLE
parent across comps (Test) ==> 16.2.11 (patreon)

### ISSUE THREAD

**Issue by mamoun86** [Rainbox-dev/DuAEF_Duik#669]
Screenshots
![Old and Beta](https://user-images.githubusercontent.com/40662938/80305702-1a6fd600-87c7-11ea-9323-ed81126a958a.jpg)

[Goyle-precomp-leg (Old and Beta) folder.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/4535154/Goyle-precomp-leg.Old.and.Beta.folder.zip)

**System (please complete the following information):**
 - OS:  windows 10
 - Version of After Effects: 17.0.6
 - Version of Duik: 16.2.11

**Comment by Nico-Duduf** [comment]
Thanks for your feedback!

**Comment by Nico-Duduf** [comment]
I've found the issue: the prject uses the "Legacy Extendscript" expresssion engine and it seems my new expression don't work with it.

It will be fixed in the next update very soon, in the meantime if you switch to the "javascript" engine (in the project settings) it will work again

**Comment by Nico-Duduf** [comment]
fixed!
will be available in a few days
