### ISSUE TITLE
Bug in Duik Bassels Edit Controllers Panel

### ISSUE THREAD

**Issue by Webscribe** [Rainbox-dev/DuAEF_Duik#672]
**Describe the bug**
If I select a controller and use the GET button to pull in the color and size values it doesn't matter what the size is set at, instead of pulling in the size value of the selected controller's icon it changes that that value Custom (thereby changing it's size instead of just recording it). 

**To Reproduce**
1. I select the control layer.
2. I click the GET button.
3. The size changes to custom, thereby changing the original size of the button.

**Error description, if any**
File: 
Line number:
Error message: none

**Expected behavior**
I expect the GET button to place the selected controller's icon values into the Edit Controllers Panel so I could then select other controllers and set them to those values.

**Screenshots**
Not applicable.

**System (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Version of After Effects: 17.0.6
 - Version of Duik: 16.2.8

**Additional context**
Other than this minor problem, the Eid Controllers panel functions perfectly for me.

**Comment by Nico-Duduf** [comment]
Thanks for your feedback, I'll fix this in the next update (16.2.11)

**Comment by Nico-Duduf** [comment]
Well, it's a bit more complicated than I thought and the fix won't make it in 16.2.11 (which is released tomorrow).
It will be in 16.2.12 a bit later, sorry!

**Comment by Nico-Duduf** [comment]
fixed in 16.2.14 available next week, sorry for the delay
