### ISSUE TITLE
Parent across compositions won`t parent scale

### ISSUE THREAD

**Issue by Alemotion8** [Rainbox-dev/DuAEF_Duik#673]
**Parent across compositions won`t parent scale**
Was super exciting with this feature since i`m getting deep in Duik, but found this little bug when i parent a comp to a null object and won`t affect scale, only position and rotation.

**Expected behavior**
Parent all parameters across compositions

**System (please complete the following information):**
 - OS: High Sierra 
 - Version of After Effects: 2020
 - Version of Duik: 16.2.9

![Screen Shot 2020-05-05 at 6 21 30 PM](https://user-images.githubusercontent.com/64661048/81117617-c3bc7780-8efd-11ea-965b-d78b04891f71.png)
![Screen Shot 2020-05-05 at 6 21 35 PM](https://user-images.githubusercontent.com/64661048/81117622-c61ed180-8efd-11ea-9095-9263aecd272a.png)

**Comment by Nico-Duduf** [comment]
We're working on this !

it should be available soon, we're testing the feature on https://patreon.com/duduf
