### ISSUE TITLE
Facial Structures

### ISSUE THREAD

**Issue by ZaFischy** [Rainbox-dev/DuAEF_Duik#674]
It would be very awesome to be able to have facial structures implemented into DUIK as well. That way, facial expressions could become easier to people all over the world and allow more people to try and animate with adobe as well! Making DUIK and even more versatile Plug-in, and make animation a much more fun project!

Whether the project be based off the skeletal structures that are currently being used for character rigging in DUIK, or a different order of events relating to facial mapping, or/and probably a simpler way to do it, using the layers that someone has previously made to create pre-made or default expressions. Then, someone could click a button to form a new expression. The speed at which it turns into the expressions could be adjustable too.

**Comment by Nico-Duduf** [comment]
It's not very clear how you'd like this feature to work; could you explain more precisely, or post an Aep showing how the face would be rigged?
I don't really understand what you mean with facial structures; it would make sense for bones in 3D but in the After Effects context I'm a bit lost

For now, using mostly the connector, and custom structures for the hair, seems to work well for most people

**Comment by ZaFischy** [comment]
Yeah I apologize, I wasn’t looking hard enough and saw that I had missed the section of Duik that did have controllers for the mouth, nose, etc... just shows that people gotta look a little harder sometimes including me!


Sent from Yahoo Mail for iPhone


On Friday, May 8, 2020, 08:52, Nicolas Dufresne <notifications@github.com> wrote:




It's not very clear how you'd like this feature to work; could you explain more precisely, or post an Aep showing how the face would be rigged?
I don't really understand what you mean with facial structures; it would make sense for bones in 3D but in the After Effects context I'm a bit lost

For now, using mostly the connector, and custom structures for the hair, seems to work well for most people
