### ISSUE TITLE
MouseOver AutoRig-IK

### ISSUE THREAD

**Issue by MrPolo67** [Rainbox-dev/DuAEF_Duik#675]
**Describe the bug**
Mouse Over on Autorig options

**To Reproduce**
1. Just Mouse Over Autorig options
2. 
3. 

**Error description, if any**
File: Duik Bassel 2
Line number: 14563
Error message: can't read.. screen freeze

**Expected behavior**
no time to expect anything.

**Screenshots**
![Bug_2020_05_08_MouseOver_Auto Rig-IK](https://user-images.githubusercontent.com/65020969/81405414-dc17d680-9137-11ea-8c8d-4a33c69b9263.jpg)

**System (please complete the following information):**
 - OS: win10
 - Version of After Effects: cc2019 : v16.1.2(build55)
 - Version of Duik: Bassel 2 v16.2.10

**Additional context**
It happens often and  not only with auto-rig

**Comment by Nico-Duduf** [comment]
Your screenshot does not show the bottom line (status bar) of the window with the specific error, so I can't know what's wrong, could you post it again?

I believe that's a bug in Ae, have you tried with a more recent version?

In the meantime, deactivating javascript debugging in the preferences will probably solve the issue

**Comment by MrPolo67** [comment]
Sorry i don't saw your answer.
this a new screenshot... for the bug which is always the same in all those situations.

There is only the message at the bottom :  undefined n'est pas un objet
![Bug_2020_05_08_Rig-IK_2](https://user-images.githubusercontent.com/65020969/81408776-1f754380-913e-11ea-9978-7640b18c3a6a.jpg)

**Comment by MrPolo67** [comment]
Merci pour la réponse.

la ligne en bas disait "undefined n'est pas un objet"

J'ai fini par trouver le bouton debug javascript dans les préférences ->
"Modules de script et expressions".. les coquins ils l'ont déplacé.

Le ven. 8 mai 2020 à 14:55, Nicolas Dufresne <notifications@github.com> a
écrit :
