### ISSUE TITLE
Rename bones/pin puppet

### ISSUE THREAD

**Issue by MrPolo67** [Rainbox-dev/DuAEF_Duik#676]
**Describe the bug**
open extendtoolscript and freeze all

**To Reproduce**
1. select pins puppets
2. want to rename and clic to change 'rename layer' to 'rename bones"
3. crash

**Error description, if any**
File: 
Line number:
Error message:  can't read

**Expected behavior**
Rename pin puppets

**Screenshots**
![Bug_2020_05_05_Rename_Bones](https://user-images.githubusercontent.com/65020969/81406049-277eb480-9139-11ea-8655-bbe06ff924d1.jpg)

**System (please complete the following information):**
 - OS: win10 pro v1903, OSv 18362.778
 - Version of After Effects: cc2019, v16.1.2
 - Version of Duik: bassel 2 v16.2.1

**Additional context**

**Comment by Nico-Duduf** [comment]
same issue than 
#675
