### ISSUE TITLE
IK constraint does not build and locks up DUIK until AE reboot

### ISSUE THREAD

**Issue by chad-exc** [Rainbox-dev/DuAEF_Duik#682]
**Describe the bug**
Running the autorig/IK function does not complete and locks up DUIK from running until AFX is rebooted. It stops at the "magic is happening screen*. I have enabled javascript debugging but no errors or windows pop up. Have tried with latest version of DUIK and one version back. Happens the same on 2019 and 2020 AE. I blew away prefs for 2020 and still did not fix the issue. I crowdfunded the current version of DUIK, would be great if I could get this looked at as it's for an active project. 

**To Reproduce**
1. Download this simple AE scene.
[Google Drive Link](https://drive.google.com/open?id=1GE5Iw78UvvG7RX4cDDxmGhAg0-4bdKiE)
2. Select the black square and then the blue square
3. run the Autorig/IK function

**Error description, if any**
File:  NA
Line number: NA
Error message:  NA

**Expected behavior**
Expected it to create a IK constraint. This was working fine for quite a while, and then suddenly it just stopped working today. I had created some IK constraints, undid them, and redid them (to correct positioning). Suddenly/abruptly it just stopped. 

**Screenshots**
If applicable, add screenshots to help explain your problem
Screenshot of my scene
![duik_before](https://user-images.githubusercontent.com/18503824/82287882-d5bf0100-9966-11ea-86a5-15c8b9ba2e96.png)
What my AE window looks like when it gets stuck. .
![duik_after](https://user-images.githubusercontent.com/18503824/82287905-e53e4a00-9966-11ea-9248-d30bf7ab36a7.png)
**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: Latest 2020
 - Version of Duik: 16.2.10 and the latest version as well. 

**Additional context**
Other than just undoing and deleting IK constraints I wasn't happy with, there was no other context to give, just normal rigging.

**Comment by Nico-Duduf** [comment]
"Fixed": Duik will not freeze anymore in this specific case, but as it's a user error, the intended result will not be achieved.
