### ISSUE TITLE
Kleaner causes Expression error

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#684]
**Describe the bug**
Using the Kleaner on a simple keyframed position property causes an expression error.

**To Reproduce**
1. Add simple position animation (2 keyframes)
2. Use Kleaner
3. Get Expression error

**Error description, if any**
See screenshot in the uploaded files

**Expected behavior**
no expression errors

**Screenshots**
see attachments
[Kleaner-errors.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/4671508/Kleaner-errors.zip)

**System (please complete the following information):**
 - OS: MacOS 10.15.4
 - Version of After Effects: 17.0.6
 - Version of Duik: 16.2.11

**Comment by Nico-Duduf** [comment]
Woooops!
That's a very nasty bug, it's surprising you're the only one mentionning it!
It's fixed, I'll release the update ASAP, sorry for this one!

**Comment by reneandritsch** [comment]
Dear Nicolas! Thank you, I actually found it by coincidence, when I downloaded the update and read about the “new” Kleaner in the Crowdfunding Campaign I quickly tried some stuff, et voilà ;-)
