### ISSUE TITLE
Auto-parent

### ISSUE THREAD

**Issue by Soterr8** [Rainbox-dev/DuAEF_Duik#685]
**Is your feature request related to a problem? Please describe.**
When one of chosen layers is parent layer to one of them, i can't tie layers because for example 5th layer is parent layer for 1st layer and pick whip work similiar. Could you fix this in DUIK?

**Describe the solution you'd like**
Parent last layer> NONE and All layers are snapped to the last selected layer, even if it was related to one of them.

**Describe alternatives you've considered**

**Additional context**
![2](https://user-images.githubusercontent.com/65598158/82872330-96327f00-9f3b-11ea-97fc-3e48b54fcae4.png)
![1](https://user-images.githubusercontent.com/65598158/82872335-97fc4280-9f3b-11ea-88be-22771ded30e5.png)

**Comment by Nico-Duduf** [comment]
Do you know you can just Ctrl+Clic on the pickwhip of your fifth layer to unparent it? That's very quick, a lot quicker than changing this feature in Duik, which is a lot of work because we'd have to also check for the case when there are intermediate children to see if the layer needs to be unparented.

**Comment by Nico-Duduf** [comment]
And in the case there are intermediate children, there's no way to know which one the user would like to unparent.

It's up to the user to define the relations between the layers, not to Duik, which just have to do what you tell it to do, and nothing more, especially not guess what the user wants in his place.
A parenting tool should not unparent anything.

**Comment by Soterr8** [comment]
I know ctrl+click shortcut, i understood all, really sorry for taking your time!
