### ISSUE TITLE
Auto-Rig crashes after only making two controllers

### ISSUE THREAD

**Issue by Camscws** [Rainbox-dev/DuAEF_Duik#689]
**Describe the bug**

**To Reproduce**
1. Rig up Camel structure, 4 points in the tail, no foot, only thigh, calf and hooves.
Freezes on "magic is happening" composition, and does not continue. Only three controllers visible, none properly linked.
2. 
3. 

**Error description, if any**
File:  N/A
Line number:
Error message: 

**Expected behavior**
An animal structure

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 
 - Version of Duik: 

**Additional context**

**Comment by Nico-Duduf** [comment]
Can you post the aep with the structures or a screenshot where the structures are visible please?

**Comment by Nico-Duduf** [comment]
I've found the issue, fixed in 16.2.14 available next week

Thanks for your feedback
