### ISSUE TITLE
Remove Controllers as nulls option

### ISSUE THREAD

**Issue by SEGA201** [Rainbox-dev/DuAEF_Duik#690]
**Describe the bug**
I used structures and Auto-Rig and everything was fine, as usual I created structures, selected them and clicked Auto-Rig, and everything was well attached and the controller was created, but at one point a null object was created instead of the controller and after that whatever I did which versions of duik would use, a null object is created instead of the controller. If you use the structure of the legs or arms, then duik simply creates a null object, and if you try to bind the Spine or Hominoid structure at once, then all layers are mixed up in places, and for some structure 1-2 controllers are created, but for everything else null object.

**To Reproduce**
1.  Create a structure
2.  Click Auto-Rig
3.  See a null object instead of controller

**Expected behavior**
To create a controller instead of a null object

**Screenshots**
![1166](https://user-images.githubusercontent.com/56382023/84107644-e246ee80-aa26-11ea-904b-d6d06b2cb633.PNG)

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: CC2018
 - Version of Duik: 16.2.6 and 16.2.13

**Comment by Nico-Duduf** [comment]
Can you check in the controller edit panel if they're set to use nulls instead of shape layers?
Also, is there any error shown when you run the auto-rig?

**Comment by SEGA201** [comment]
switch nulls to the shape layers in the controller edit panel helped, thanks.
but found another problem.
created another thread for this.

**Comment by Nico-Duduf** [comment]
I think I'm going to remove the support for controllers as nulls, it's too much work and they're always broken :)
