### ISSUE TITLE
Spring unselects the layer when applied

### ISSUE THREAD

**Issue by Jissse** [Rainbox-dev/DuAEF_Duik#692]
Select a prop, apply a spring, and the layer is "unselected", you have to click on it again to see its effects panel and change stuff.

**Comment by Nico-Duduf** [comment]
Can't repro, what was the property?

**Comment by Nico-Duduf** [comment]
I've made some changes anyway which should fix the issue, let me know if you still have it with 16.2.14 (release soon)
