### ISSUE TITLE
Bug with structures in 3D mode

### ISSUE THREAD

**Issue by The-Chacal** [Rainbox-dev/DuAEF_Duik#697]
**Describe the bug**
When Structures are in 3D mode, the auto Rig crashing applying its magic

**To Reproduce**
1. Have your structures in 3D
2. Click on auto Rig ;)

**Expected behavior**
   I'd rather have Duik to uncheck the 3D mode( if the Z value is not modified ) or just warn me of the problem and stop before doing anything.

**System (please complete the following information):**
 - OS: windows 10
 - Version of After Effects: 17.1.1
 - Version of Duik: 16.2.13

**Comment by Nico-Duduf** [comment]
fixed
