### ISSUE TITLE
Bug with adding bones

### ISSUE THREAD

**Issue by The-Chacal** [Rainbox-dev/DuAEF_Duik#698]
**Describe the bug**
   The adding bones tool does not detect that the corners of my puppet tool effet are in advanced mode -> being in 2D instead of 3D mode solve this but still...

**To Reproduce**
1. have a puppet with several advanced mode corners on your layer (in 3D mode)
2. click on add Bones
3. 

**Expected behavior**
   The buttons should add the advanced corners icons but only apply the bones as if the corners were position corners only.

**System (please complete the following information):**
 - OS: windows 10 
 - Version of After Effects: 17.1.1
 - Version of Duik: 16.2.13

**Additional context**

**Comment by Nico-Duduf** [comment]
fixed
