### ISSUE TITLE
parent path constraint

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#701]
Voir pour améliorer le parentage d'un path + path constraint.

Actuellement si on parent à un objet, le path constraint "saute" s'il n'est pas à [0,0]

Explication/exemple
[https://puu.sh/G3XEW/47dd275f1e.mp4](https://puu.sh/G3XEW/47dd275f1e.mp4l)

**Comment by Nico-Duduf** [comment]
en fait je pourrais pas corriger ça exactement comme ça, c'est pas possible. Par contre j'améliore un peu la facon dont ça se comporte si tu ne parentes QUE le calque avec le chemin
