### ISSUE TITLE
Kleaner amplitude/follow through

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#702]
Je te le met juste pour idée après en avoir discuté ensemble, pourquoi pas un amplitude sur le follow through comme sur le anticipation.
Mais si l'anime "saute" du coup, il vaut mieux laisser comme c'est actuellement, en bidouillant avec les réglages et les clés on peut trouver les bon setting

**Comment by Nico-Duduf** [comment]
ça va péteeeeeeeeer. Déso je peux pas le faire, mais j'y resongerai quand je ferai la version redux pour 16.3
