### ISSUE TITLE
Animation blender / change source

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#704]
Éventuellement l'ajout d'un effet controle de calque pour modifier la source du controle de l'animation blender en cas de duplication de l'anim

**Comment by Nico-Duduf** [comment]
je comprends pas vraiment de quoi tu parles quand tu parles de source du controle ?

**Comment by kanadiou** [comment]
par exemple si on fait un clic de souris, on duplique la sous comp "clic souris" qu'on vient remplacer dans une nouvelle comp parent.
Ainsi on a plusieurs fois la même sous comp mais dupliquée sans avoir à la changer mais pour faire la même chose ailleurs.
Il faut donc remplacer la source - la sous comp "clic souris" ainsi que la source du parent.

Je sais pas si je suis plus clair ?

on a donc 
comp "master 1" - sous comp "clic souris 1"
comp "master 2" - sous comp "clic souris 2"
etc

**Comment by Nico-Duduf** [comment]
Wontfix: pas de nouvelle feature sur l'animation blender actuel, qui sera entièrement remplacé dans 16.3
