### ISSUE TITLE
Path constraint / change source

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#705]
Ajouter un layer control si on duplique les layers pour pouvoir modifier rapidement la source du path ou inversement la source du path constraint

**Comment by Nico-Duduf** [comment]
pas possib', parce que si on peut changer de calque, on peut pas changer de path par contre, le path est hardcodé dans l'expression, pas le choix. Du coup, on peut pas switch de calque, faudrait un truc pour sélectionner le path en même temps, et ça, ya pas dans Ae
