### ISSUE TITLE
animation blender issue with javascript

### ISSUE THREAD

**Issue by kanadiou** [Rainbox-dev/DuAEF_Duik#707]
Petit souci avec animation blender, qui marche en legacy mais pas en javascript.
Pas d'erreur, juste ça marche pas

Dis moi si tu veux mon projet ;)

**Comment by Nico-Duduf** [comment]
Je n'arrive pas à repro sur 17.1.1 ni sur la dernière beta, ça marche avec les deux moteurs dans mes tests.

Je suis preneur de tout projet montrant le problème !

**Comment by kanadiou** [comment]
voici un fichier de test.
ne marche pas chez moi en javascript sur ae 17.1.1
marche en legacy

[test anim blender.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/4961255/test.anim.blender.zip)

**Comment by Nico-Duduf** [comment]
Gracias!

**Comment by Nico-Duduf** [comment]
apparemment c'est un bug Ae qui a été réparé ; il faut me confirmer que ça remarche chez toi kana ;)
