### ISSUE TITLE
Animation blender not working with latest Ae updates 

### ISSUE THREAD

**Issue by pietroli** [Rainbox-dev/DuAEF_Duik#708]
Depuis la dernière mise à jour d'after effects le mixeur d'animation ne fonctionne plus sur mac ou sur pc.
il arrive qu'une erreur d'expression s'affiche mais ne reste pas.

**Comment by Nico-Duduf** [comment]
Il faut passer le moteur des expressions en legacy/extendscript apparemment pour que ça fonctionne, en attendant que je le corrige

**Comment by Nico-Duduf** [comment]
Attention : merci de mettre des titres précis pour les reports

**Comment by Nico-Duduf** [comment]
Aussi, si c'est une mise à jour d'After qui a cassé l'outil, je vais avoir besoin de savoir quelle version d'after effects exactement

**Comment by Nico-Duduf** [comment]
possible duplicate: #707

**Comment by pietroli** [comment]
Je préfère le prendre avec légèreté car à mon retour de vacance, une demande urgente d'un client qui demande des modifs sur un motion long et complexe monté en majorité avec le mixeur d'animation, ca pique.
Je te laisse imaginer ma frustration d'avoir à modifier toutes les animes en catastrophe.
La bidouille de repasser le projet en Legacy n'est pas envisageable car il y a bien d'autres Script utilisés sur ce projet.
Je veux bien comprendre que le Plug-in reste gratuit par conviction "idéologique" mais je préfère parfois payer et avoir confiance en mes outils surtout que je participais au Patreon (malgré mes petits moyens) justement par soucis du développeur.
Je comprend que ce sont des choses qui peuvent arriver et qu'il me revient la responsabilité de prévoir et de m'adapter à toute éventualité, mais je reste quand meme sur ma faim sur ce coup-ci.
Cordialement.

**Comment by Nico-Duduf** [comment]
Bah désolé si After introduit de nouveaux bugs !

Avec l'équivalent d'un quart-temps que ramène le patreon, on fait ce qu'on peut. Si une maj d'After pète tout, c'est contre Adobe qu'il faut raler, même si ici on essaie de contourner les soucis comme on peut. Tu as de la chance qu'on répare les bugs dans les jours qui suivent les signalements ! Il y a une mise à jour de Duik toutes les trois semaines en ce moment...

Si Duik était payant, on aurait le même problème ici, des fois, il y a des bugs dans les softs, c'est comme ça. Ca marchait avant de mettre à jour After, ça marche plus après, on peut pas prévoir. Et payant ou pas, on corrige autant et aussi vite que possible.

Par contre, pour ça, il FAUT que les utilisateurs fassent des bugs reports corrects, avec suffisamment d'info : je redemande : de quelle version d'After est ce qu'on parle ? Pour que je puisse corriger plus vite, faut me donner les infos, sinon je perds un temps fou à trouver les problèmes avant même de pouvoir les résoudre.

Tu as posté le bug il y a deux jours, j'allais poster une correction samedi, ça va hein. J'ai presque envie de retarder la sortie de la mise à jour tiens.

**Comment by Nico-Duduf** [comment]
Cela étant dit : je pense pas que passer en legacy ne casse quoi que ce soit, un bon 90% des expressions qui marchent en javascript marcherront en extendscript, tu as testé ?

Si des devs utilisent des trucs compatibles uniquement javascript, c'est pas sympa pour les utilisateurs... Et je te parie ce que tu veux que ce ne sont pas des devs de softs libres et gratuits qui font ça.

**Comment by Nico-Duduf** [comment]
Re,
Je n'arrive même pas à reproduire le souci ici, j'ai vraiment besoin de plus d'infos pour le trouver et le réparer.
Quelle version d'After effects exactement ?
Sinon un projet aep où ça ne marche pas serait le bienvenu pour que je puisse y jeter un oeil

**Comment by pietroli** [comment]
yep,
la version d'after effects est la 17.1.1 (la dernière à ce jour). je ne peux malheureusement pas te fournir le projet concerné mais le problème c'est qu'il y a aucune erreur c'est juste que ca ne marche pas tout simplement.

**Comment by Nico-Duduf** [comment]
Ici dans mes tests tout fonctionne, donc il me faut vraiment des détails, ou par exemple un autre projet qui reproduit le problème sinon on ne peut rien faire.

Note : quelle est la langue d'After ?

**Comment by pietroli** [comment]
l'after est en français, je vais voir quand j'aurais le temps pour me pencher sur la question et t'envoyer un projet
