### ISSUE TITLE
Bug Switch IK/FK

### ISSUE THREAD

**Issue by The-Chacal** [Rainbox-dev/DuAEF_Duik#710]
**Describe the bug**
   When I click on the switch between IK and FK it does nothing when I want to go from FK to IK, it works perfectly from IK to FK though.
   Maybe comes from the fact I use zéros for my controllers?

**To Reproduce**
1. Set your controller in FK mode
2. Click on the button to switch from FK to IK or the option "put IK on FK"

**System (please complete the following information):**
 - OS: win 10
 - Version of After Effects: 17.1.1
 - Version of Duik: 16.2.15

**Comment by Nico-Duduf** [comment]
Fixed!

It was just a stupid mistake....
