### ISSUE TITLE
Expression error regarding connectors after extracting controllers 

### ISSUE THREAD

**Issue by DevMayCare** [Rainbox-dev/DuAEF_Duik#716]
**Describe the bug**
After extracting controllers into a new composition expression errors can occur.

For certain scenes with connectors, the path to the connector in the original composition is not updated
causing expression error(s).

Workaround:
Replace the relative path in the expression with an absolute path, f.e. changing:
var connectorLayer = thisComp.layer("C | Connector");
to:
var connectorLayer = comp("Squeaker").layer("C | Connector");

**To Reproduce**
1. Open the attached scene. 
2. Observe the expression error or
3. Create a new composition.
4. Add "Squeaker" comp to the composition.
5. Extract controllers from the newly added "Squeaker" comp.
6. Observe the expression error.

**Error description, if any**
File: Squeaker_rig_extracted
Line number: 3
Error message: "Layer named 'C | Connector' is missing or does not exist."
[Squeaker_rig_extracted folder.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/5050750/Squeaker_rig_extracted.folder.zip)

**Expected behavior**
No expression errors should occur when extracting controllers from a scene with connectors.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Win10 Pro
 - Version of After Effects: 17.1.2. (Build 37)
 - Version of Duik: v16.2.16

**Comment by Nico-Duduf** [comment]
fixed in 16.2.17 available very soon
