### ISSUE TITLE
Hominoid structure - Heel not translated in French

### ISSUE THREAD

**Issue by AurelienDelamare** [Rainbox-dev/DuAEF_Duik#717]
**Describe the bug**
When creating an Hominoid structure with french version of Duik, heel layer is in english.

**To Reproduce**
1. Click on Hominoid structure

**Screenshots**
![Heel](https://user-images.githubusercontent.com/58236447/89784341-c9d37d00-db18-11ea-9460-246201b0131b.JPG)

**System (please complete the following information):**
 - OS: Win 10 Professionnel 64bits version 1909
 - Version of After Effects: 17.1.1
 - Version of Duik: 16.2.15

**Comment by Nico-Duduf** [comment]
fixed in 16.2.17 available in a few minutes ;)
