### ISSUE TITLE
2D camera rig problem

### ISSUE THREAD

**Issue by ArtemSh-Hd** [Rainbox-dev/DuAEF_Duik#721]
** Please describe the error **
I propose to take into account the peculiarity of the expression Wiggle in AE

** Play **
for example, if you put Tilt = 120, the expression recalculates it in 360 (type = fixed)

**Expected behavior**
 Tilt = 120

**Screenshots**
![image](https://user-images.githubusercontent.com/69811802/90423063-7b981e00-e0c4-11ea-9f00-7340ee409569.png)

**System (please complete the following information):**
 - OS: windows 10
 - Version of After Effects: 16.1.2
 - Version of Duik: 16.2.16

**Comment by Nico-Duduf** [comment]
fixed in 16.2.17 available very soon
