### ISSUE TITLE
Duik version is not updated after an update from 16.2.16 to .17

### ISSUE THREAD

**Issue by woozygoozy** [Rainbox-dev/DuAEF_Duik#726]
**Describe the bug**
I have updated the script to 16.2.17 the usual way - replace the script in the ScriptsUI folder, but the version at the bottom when loaded still reads 16.2.16

A friend also has the same issue.

I am on a Mac running AE version 17.1.3 build 41

**Comment by Nico-Duduf** [comment]
fixed!
