### ISSUE TITLE
One Click Auto-Character Creation with Limber Style Arms and Legs that comes with Character Animation Library

### ISSUE THREAD

**Issue by Abhilashanurag** [Rainbox-dev/DuAEF_Duik#728]
Hi Team Duik,

You are awesome,

I have a few FEATURE REQUESTS.

1. With one click Duik creates A CHARACTER with Arms and Legs are like Limber (aescript) and Full rotating body and a dummy head. (Head and body can be modified as per the animators or users' requirements with their artwork.)

2. A Premade library of Character Animations Inside DUIK like talking, jumping, discussing, fear, running, actions and regular activities, etc( This should work for the above default "one-click character creation"-. And give to save new animations and extend this Animation library.

**Comment by Nico-Duduf** [comment]
1. There will be this kind of stuff with the new OCO (open cut out format) we're developping

2. It's an idea we've had for a long time, but not as easy as it seems, all characters are different. This being said, there will be some kind of animation libraries in the future.
