### ISSUE TITLE
Problem with additional option menu

### ISSUE THREAD

**Issue by Kamsus** [Rainbox-dev/DuAEF_Duik#729]
Hi Duduf! .. look, here's a bug. version 16.2.17 (all 16.х.хх). the program window is maximized to full screen. when you click on the additional options circle (Auto-rig&IK), the options menu opens outside the screen. ALWAYS (except god mode)! Whoever does not guess to move the main window of the program, he won’t guess.
![1](https://user-images.githubusercontent.com/71124997/92899214-cea58c80-f448-11ea-8dd7-82327b9538e1.jpg)
![2](https://user-images.githubusercontent.com/71124997/92899263-da914e80-f448-11ea-8589-730f66779d56.jpg)

From Russia with love...

**Comment by Nico-Duduf** [comment]
Thanks for the feedback.
The UI scripting is so old and crappy in Ae I'm not sure how I can fix that, but I'll try and see what can be done in the next update

**Comment by Nico-Duduf** [comment]
fixed
