### ISSUE TITLE
Problem with "options" 

### ISSUE THREAD

**Issue by kotydwa76** [Rainbox-dev/DuAEF_Duik#746]
**Describe the bug**
I've installed the latest version and now I have a problem: whenever I click the "option" button next to leg/arm/tail/etc. all Duik feautes become sort of inactive. Options window doesn't appear. 

**To Reproduce**
1. Click on the "dot" next to the name of the rigging featur (arm, tail...) and Duik panel stops to respond.

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
It should display small window with extra options like number of bones in tail but doesn't

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10 
![Przechwytywanie w trybie pełnoekranowym 12 10 2020 151316](https://user-images.githubusercontent.com/72746131/95750690-cdf95380-0c9d-11eb-896a-2658a3160a3b.jpg)

 - Version of After Effects:  CS6
 - Version of Duik: 16.2.18

**Additional context**

**Comment by Nico-Duduf** [comment]
It's probably an issue with Ae CS6, in which case I'm not sure I can do anything about it.

Can you enable javascript debugging and post a screenshot of any message/window which is shown when you try to open an option panel?

Thanks

**Comment by kotydwa76** [comment]
I have no slightest idea how debuggin works, I'm just "fire and forget" user. Expressions is all I know. Scripts are beyond me.

When I hover over the panels buttons it still shows the labels
It acts as if this pop up window was somewhere but invisible.

![Przechwytywanie w trybie pełnoekranowym 12 10 2020 152342 bmp](https://user-images.githubusercontent.com/72746131/95751522-08172500-0c9f-11eb-9edf-224f5e54e0be.jpg)

**Comment by kotydwa76** [comment]
Is previous version available to download somewhere?

**Comment by Nico-Duduf** [comment]
I mean, in the preferences of After Effects, you have a "javascript debugging" option to switch on, that's all.
Then, when a script fails, it will show either an error, or even the script editor/debugger, and that's what I need to see

**Comment by kotydwa76** [comment]
Something like this?
![Przechwytywanie w trybie pełnoekranowym 12 10 2020 153609 bmp](https://user-images.githubusercontent.com/72746131/95752734-c4bdb600-0ca0-11eb-931b-50c1ad5b91ef.jpg)

**Comment by kotydwa76** [comment]
I had no this problem yesterday. I've installed new version today and - bang.

**Comment by Nico-Duduf** [comment]
Thanks for the screenshot, that helps.

I'll have a look at that and may be able to fix it. It's definitely an issue with CS6 and the way now Duik handles the popups. But you really should update After Effects, I won't always be able to make Duik work on versions of After Effects which are older than 10years.

**Comment by kotydwa76** [comment]
I'm on the budget. Maybe if I'd find a an overseas client but so far I have to squeeze the very last juice from it. You wouldn't believe how long I've been working on CS3.

**Comment by Nico-Duduf** [comment]
I understand that, and that's why I'm keeping Duik free, and I try to keep it working on CS6 ;)

My issue is that I don't have CS6 anymore, and no way to install it again legally :'(

**Comment by kotydwa76** [comment]
I will updat it eventualy. That day will come.
I'm old fashioned. I like to own things you know... I don't like the thought that when my subscription ends I won't be able to open my own files... I hope I'll get some holiday bonus so I'll be able to donate some again. You do a great job.

**Comment by kotydwa76** [comment]
BTW: I like the "tail" feature. Great for tentacles and other stuff. Would it by possible to make in some future versions a stretching option? To animate te lenght of the, say, a tentacle by changing the lenght of the bones. I'm working on short fan film based on "Maniac Mansion" games and there is a walking sentient tentacle. I'm just testing different ways to animate it and found it could be helpfull as this "walking" is more like jumping on one leg (with a very sticky shoe). Just a thought - I'll manage it with existing tool. Once again thanks for what you do for us!

**Comment by Nico-Duduf** [comment]
That's a good suggestion!
Could you open a feature request for it?
https://github.com/Rainbox-dev/DuAEF_Duik/issues/new?assignees=&labels=Enhancement&template=feature_request.md&title=


Thanks a lot!

**Comment by kotydwa76** [comment]
Sure.. I'm totaly new to Github. Interesting place :)

**Comment by Nico-Duduf** [comment]
It's veeery useful to track bugs and manage feature requests!

**Comment by Nico-Duduf** [comment]
Back to the option with the options popup: it should be fixed in the update available today or tomorrow; let me know if you still have an issue after the update!
