### ISSUE TITLE
Scale Z-link broken?

### ISSUE THREAD

**Issue by Morganimator** [Rainbox-dev/DuAEF_Duik#773]
**Describe the bug**
Scale Z-link in the Camera tools doesn't seem to work.

**To Reproduce**
1. Select a layer
2. Click on "Scale Z-link"
3. Nothing happens to the layer.

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
Expected layer scale to increase or decrease depending on the distance from the camera.

**Screenshots**

**System (please complete the following information):**
 - OS: MacOS Catalina (10.15.7)
 - Version of After Effects: Ae 2020 17.5.0 (Build 40)
 - Version of Duik: v16.2.23

**Additional context**

**Comment by Nico-Duduf** [comment]
Thanks!
I'll have a look at that ASAP

**Comment by Nico-Duduf** [comment]
I just forgot that the tool won't work without a camera in the comp. I believe that's your issue, and I've just added an alert if one tries to use it without camera ;)
