### ISSUE TITLE
Function duplicatedNames[name].push is undefined

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#775]
People having this error, help us solve it!

- Make sure you're using the latest version of Duik (16.2.23)
- Does this error happen only when a project is open? If so, can you post said project here?
- Please state your OS and After Effects version

Thanks for your help

**Comment by Gregory-Ts** [comment]
[Cat.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/5562277/Cat.zip)
[https://youtu.be/VwT25Vju1pE]
Hi, I hope these files will help.
It is clearly a project base error. Im sure you will find the problem!
Thanks a lot!

**Comment by Nico-Duduf** [comment]
Thanks a lot for your feedback ,I was finally able to find what's wrong!
It was the layer named "+" which provoked the issue. It's fixed in the next update of Duik available today or tomorrow
