### ISSUE TITLE
2D Camera "Truck in" limited

### ISSUE THREAD

**Issue by ElDudie** [Rainbox-dev/DuAEF_Duik#778]
**Describe the bug**
The "Truck in / out" slider on the 2D camera settings seems limited to 1000%

**To Reproduce**
1. create a 2D camera
2. try to put something higher than 1000 on the "Truck in / out" slider
3. Voila! :)

**Expected behavior**
To past beyond this point without having to use the zoom

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 2020
 - Version of Duik: 16.2.22

Thank you so much for all your effort and for spreading so much love in useful tools way :)

**Comment by Nico-Duduf** [comment]
fixed in the new version available today or tomorrow, thanksfor the feedback!

**Comment by ElDudie** [comment]
Hey Nicolas!
Oh man thank you very much, really it's amazing the amount of effort, work and love you put into these tools, amazing and super useful tools, thanks!!
Appreciate it so much!!

Be safe and cheers!!

Carlos Arandia
________________________________
