### ISSUE TITLE
Preferences for Sanity report and refresh button

### ISSUE THREAD

**Issue by reneandritsch** [Rainbox-dev/DuAEF_Duik#780]
Dear Nicolas!

It’s been a while since I put something on GitHub but I’m back ;-) I hope you are well! Looking very much forward to beta testing the next iteration of DUIK.

The “Sanity” feature is great! Do you have plans for Sanity preferences? I guess this would be a nice idea because everybody has different aspects for keeping their projects in order. I for instance also use a subfolder for my main comp. So it would be great if the DUIK brain would not flag it with an info and just have it as “OK”

![project folders](https://user-images.githubusercontent.com/38455050/101508444-f937b080-3977-11eb-8f30-f27a938c6848.png)

Also does the user have to wait until the panel refreshes if something was changed? The use might want to trigger the testing with a refresh button.

Thanks and all the best, René

**Comment by Nico-Duduf** [comment]
Hi René and welcome back :)

I'm always glad to get smart feedback from you ;)

Yes there will be settings to take this kind of difference into account; I hope to be able to release an update sepcifically for this in january. There will also be a specific "DuSan", a separate script just for that, maybe with a bit more options.

The refresh button is a very good idea, I'll add that very soon, it's quick and easy!

Thanks a lot! Cheers!

**Comment by Nico-Duduf** [comment]
A side note: you can currently disable the tests you don't need/do not suit you in the sanity panel, with one of the buttons

**Comment by reneandritsch** [comment]
Thanks Nicolas. If the magic wand is “on” the script checks the status all the time, correct? The screw driver is the refresh button bit just for the single test, correct?

**Comment by Nico-Duduf** [comment]
Done!

Available soon

I realize I did not answer your questions:

- When tha magic wand is on, Duik fixes any problem as soon as it's detected, automatically
- The screwdriver is used to manually fix the problem corresponding to the test

I'm writing a doc to be added in the guide about all of these ;)

**Comment by reneandritsch** [comment]
Thank you!
