### ISSUE TITLE
Duik Fails when Accessing the settings menu "Execution Halted" 

### ISSUE THREAD

**Issue by riccasmail** [Rainbox-dev/DuAEF_Duik#784]
When Trying to access any of the settings tabs notably the setting menu Duick fails at scripts level. just hovering over the "rookie" option will crash it out and pop up the script editor, then give me a popup that says "unable to execute script at line 15538. execution halted". this happens when trying to change any setting across the entire UI.  I have tried running the script in every way, including manually installing it and installing it through "file/scripts/install scriptUI" as well as just running it from file. 
i have "Allow Scripts to Write files and access Network" selected

1. open Settings tab. or any other settings function
2. try to click on any settings button
3. 

**Error description, if any**
File: Duik Bassel.2jsx 
Line number: 15538.
Error message: "unable to execute script at line 15538. execution halted"

**System (please complete the following information):**
 - OS: windows 10
 - Version of After Effects: 2020 
 - Version of Duik: 16.2.24

![Duik Error](https://user-images.githubusercontent.com/75744772/101655595-cb05af80-3a0f-11eb-9fa9-e42de5f01d12.JPG)

**Comment by riccasmail** [comment]
Update: I've tried this on another computer and it does not seem to be a problem. I'm not sure what's different on my system. 
any ideas would be appreciated

**Comment by Nico-Duduf** [comment]
That should be fixed on the next update, available very soon.

Note: you can avoid this kind of error by turning off the javascript debugging option in the preferences of After Effects
