### ISSUE TITLE
Possible to Bake into keyframes the Walk Cycle automation?

### ISSUE THREAD

**Issue by XAVmotion** [Rainbox-dev/DuAEF_Duik#785]
Just wondering if it would be possible to bake the WalkCycle animation into keyframes after setting up the Walk Cycle with the Automation button. Unfortunately, the expressions applied by the automation causes After Effects to crash sometimes. Same with the looper feature. Sometimes it causes to crash.

I know I can right click and turn all expressions into keyframes but it's super time consuming to go and check each individual property.

Thanks and Great work! Duik is amazing !

**Comment by Nico-Duduf** [comment]
That's a feature planned for Duik Bassel.3 / 17 ;)
