### ISSUE TITLE
Shy structures  

### ISSUE THREAD

**Issue by Baqerl** [Rainbox-dev/DuAEF_Duik#787]
HI ,I just installed Duik Bassel and by using it for while I thought adding shy layers would be a great feature .
maybe adding it next to Hide structure ? or combine it with hide structure ?
Thx

**Comment by Nico-Duduf** [comment]
Hi,

We have another script for that and much more: DuGr

Duik works well with it, it automatically creates groups for the structures, the bones, the controllers...
