### ISSUE TITLE
Duik Structures -Unable to execute script line 12805. is out of range

### ISSUE THREAD

**Issue by ShaikhSoeb** [Rainbox-dev/DuAEF_Duik#789]
**Describe the bug**
![Untitled](https://user-images.githubusercontent.com/76030943/102204077-65259600-3eef-11eb-9e78-55dfc506a7fc.png)

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: Duik Structures
Line number: 12805
Unable to execute script line 12805. is out of range

**Expected behavior**

**Screenshots**
attached

**System (please complete the following information):**
 - OS: Windows
 - Version of After Effects: latest
 - Version of Duik: latest

**Additional context**
after this i reinstall older version of duik but getting same error also i uninstall after effect and reinstall the software but it not works, please solve this asap

**Comment by Nico-Duduf** [comment]
Hi,
I can't reproduce and I can't find what's wrong at that line.

How did this happen? What were you tryuing to do? I can see Duik is already opened, so it must be when clicking on one of the buttons? Or just hovering over the panel?

**Comment by fatnmad** [comment]
Hi,
I seem to have a similar issue here with the most-recent DUIK Bassel-Update and the most-recent Adobe AE Update (Version 17.6.0 - Windows 10, German):

![error](https://user-images.githubusercontent.com/48413888/104838249-04a4c280-58ba-11eb-97e1-2d29708a84fa.jpg)


- I tried via copying the "Duik Bassel 2.jsx" files into the Scripts/Script-UI-Folder.
- I tried via installing with the "File > Scripts > Install Script-UI-Panel"
-- Installing works sofar - but when trying to open up the panel this error-msg pops up.

**Comment by ShaikhSoeb** [comment]
> Hi,
> I can't reproduce and I can't find what's wrong at that line.
> 
> How did this happen? What were you tryuing to do? I can see Duik is already opened, so it must be when clicking on one of the buttons? Or just hovering over the panel?

when clicking on the 1st button Autorig-& IK

**Comment by Nico-Duduf** [comment]
Did you add structures before running the Autorig?

**Comment by Nico-Duduf** [comment]
Or did you just select some standard layers?
