### ISSUE TITLE
Link to AME failed

### ISSUE THREAD

**Issue by Gametalic** [Rainbox-dev/DuAEF_Duik#790]
**Describe the bug**
When i want export to AME, the export failed  and a incident report windows appears

**To Reproduce**
1. Duik Animation panel on screen
2. Export to AME
3. Incident Response

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**
I suppose it's Duik Animation which causes that. Once Duik Animation file isn't in the Script Folder, the export works.

**Screenshots**

https://user-images.githubusercontent.com/66310495/103143164-8b2e1000-4711-11eb-8438-f0355a6fcacf.mp4

**System (please complete the following information):**
 - OS: Windows 10 20H2
 - Version of After Effects: 17.5
 - Version of Duik: 16.2.24

**Additional context**

**Comment by Nico-Duduf** [comment]
Can you send me the failing project file please?

**Comment by Gametalic** [comment]
By the way, i used Stardust for my project
[project gametalic.zip](https://github.com/Rainbox-dev/DuAEF_Duik/files/5743135/project.gametalic.zip)

**Comment by Nico-Duduf** [comment]
Je n'arrive pas à repro le souci mais :
- Je n'ai pas stardust
- J'ai une version plus récente de Ae
tu as toujours le souci ?

**Comment by Gametalic** [comment]
Depuis que j'ai contacté le service technique d'Adobe parce que le problème persister même après désinstallation du plugin, je n'ai plus ce soucis. Apparemment, le problème vient de ma carte graphique (Une NVidia GeForce GT 1030). On m'a fait installé un vieux pilote pour la CG et une version antérieur d'AE et AME pour une meilleure compatibilité.
 Verdict : ne pas mettre à jour ni la CG ni AE sinon c'est reparti.
 
 Je t'avais envoyé un mp sur discord là dessus pour éviter que tu ne perdes ton temps sur mon problème, je ne sais pas si tu l'as reçu.

**Comment by Nico-Duduf** [comment]
Ah non je me souviens pas ^^

En tout cas merci pour le feedback, tout va "bien" du coup (avec de gros guillemets)
