### ISSUE TITLE
Keep easing presets on expert user interface

### ISSUE THREAD

**Issue by BudyDubby** [Rainbox-dev/DuAEF_Duik#791]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to set difference number of easing on expert user interface because it was not there, the saving easing presets.

**Describe the solution you'd like**
Keep easing presets on expert user interface

**Describe alternatives you've considered**
maybe we can change the pre-determined number below easing slider?

**Additional context**
-

**Comment by Nico-Duduf** [comment]
I'll keep this in mind when re-designing the Ui of Duik 17!

**Comment by BudyDubby** [comment]
thank you very much sir
