### ISSUE TITLE
parenting between comps issue

### ISSUE THREAD

**Issue by Goofbean** [Rainbox-dev/DuAEF_Duik#792]
**Describe the bug**
Hey Duduf, it's me LENNOZ.
Quoted from Discord: I am trying to parent an animated mouth to a head, but I have a problem with parenting a layer between comps. 
You replied with "Hum, I just didn't think about that when developping this. Which was stupid because I did fix that for the extract controllers which works more or less the same way. If you can just post a bug report about it I'll fix that ASAP"
It's been 2 weeks since, and I almost forgot about this. My apologies!

**To Reproduce**
I can't exactly recall what steps I took myself, but you apparently had a pretty clear idea of the problem on discord.
As I mentioned on there:
1. The precomp containing the head-layer I wanted to parent my mouth layer on, has been offset in time; the layer doesn't start at 0:00
2. The precomp has been time-remapped
It seems that the parenting utility doesn't take modifications like those into account. 
Here's the preview again:
https://user-images.githubusercontent.com/39836649/103279779-e3de0100-49ce-11eb-9373-e8bb7e8dfbeb.mp4

**Expected behavior**

**Screenshots**
![Discord_C53toE23xO](https://user-images.githubusercontent.com/39836649/103279739-c7da5f80-49ce-11eb-80e0-f04e225d9f72.jpg)

**System:**
 - OS: windows10
 - Version of After Effects: 17.5.1
 - Version of Duik: 16.2.24

**Comment by Nico-Duduf** [comment]
Thanks! I'll fix this asap for the time offset, although thinking about it I'm not sure I can fix issues with time-remapping.

**Comment by Nico-Duduf** [comment]
I've fixed the time offset, but can't do anything about time remapping.

The fix is available in 16.2.25 available in a few days ;)
