### ISSUE TITLE
Error on line 38454 (v16.2.25)

### ISSUE THREAD

**Issue by CodySummers** [Rainbox-dev/DuAEF_Duik#799]
**Describe the bug**
After picking which language the error occurs. 

**To Reproduce**
1. Open duik
2. Pick language

**Error description, if any**
File: Duik Dassel 2
Line number: 38454
Error message: 
"Unable to execute script at line 38454. underfined is not an object"

**Expected behavior**
//

**Screenshots**
//

**System (please complete the following information):**
 - OS: Windows
 - Version of After Effects: 17.6.0 (Build 46)
 - Version of Duik: v16.2.25

**Additional context**
//

**Comment by lebronthames** [comment]
having the same problem - uninstalled last version to add new release, can't get it re-installed now

**Comment by Shin-ye-rin** [comment]
having the same problem ... help;;

**Comment by Nico-Duduf** [comment]
fixed -> 16.2.26

**Comment by biktimirow** [comment]
Hello!
Today I installed Duik 16.2.26 for the first time on my Ae 16.1.3 (build 5) running on Windows 10 19042.746
Having the same issue (Unable to execute script at line 38454. underfined is not an object) when trying to run Duik 
having issue (Unable to execute script at line 39412. File or folder does not exist) when truing to uninstall Duik
