### ISSUE TITLE
Fix "unused comp" pop-up window getting stuck

### ISSUE THREAD

**Issue by ElDudie** [Rainbox-dev/DuAEF_Duik#801]
**Describe the bug**
On the latest version (released today I think) this window just pops up and doesn't allow me to click any option nor to click anything inside After Effects, the only way to shut it off it's to hit the "Esc" key several times, but the main problem is after that happens Duik just freezes and doesn't allow to click anything on the plugin, just restart AE to make it work again.

**To Reproduce**
1. Having an unused comp on the project
2. Wat for the pop-up to show off :)

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 2020
 - Version of Duik: 16.2.26
 
 Thank you so much for all the hard work!

**Comment by craigthecreator** [comment]
I just had the exact same bug all morning, going to try switching back to the last version

**Comment by Nico-Duduf** [comment]
@craigthecreator you can disable the autofix (magic wand icon) in the sanity tests for the "unused comps" (or "main comps" maybe)

**Comment by hagar-dolev** [comment]
Just to give more details:
This happens in Mac as well, though in mac the only way I found to get out of this freeze is to ForceQuit after effects.
While it's not saving the work done (I have autosave set to 10 minutes).
Also the message it has seems to mean nothing - so does the fix of it - it does nothing in my project (When clickable, and it's the same message as reported before).
I'm trying what @Nico-Duduf you suggested 👍 
Thanks!

**Comment by ToddSauce** [comment]
Having the same issue on Mac here as well. Everything worked great until I installed the 'update'. The uninstall tool doesn't work either, as when I try to run it (via Brackets), it says, 'unexpected character "#" '. Update my AE. Nope. Duik is free and that's great, but having to force quit and redo my last few moves is a major workflow killer. How can I install the previous version?

**Comment by craigthecreator** [comment]
> @craigthecreator you can disable the autofix (magic wand icon) in the sanity tests for the "unused comps" (or "main comps" maybe)

This probably is safest bet to work around it. I had a backup of the last one just incase so i just dragged it back in and have had no problems since.

**Comment by Nico-Duduf** [comment]
Fixed issue, available in 16.2.27 later today
