### ISSUE TITLE
Pre loaded Duik panel pop-up crashing AE

### ISSUE THREAD

**Issue by yoleafbug** [Rainbox-dev/DuAEF_Duik#802]
**Describe the bug**
Sometimes when I start a project and my Duik Bassel 2 UI panel is docked, I get this pop-up that freezes After Effects (and makes me have to force quit): 
"Fix Unused Compositions...2 seemingly unused comps. have been found in this project. What do you want to do with them?..." 

**To Reproduce**
1. Opening After Effects with the Duik Bassel 2 panel open. 
2. I believe it only happens in projects where I've already used Duik on. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Microsoft Windows 10
 - Version of After Effects: 17.6
 - Version of Duik: 16.2.27

**Additional context**

**Comment by Nico-Duduf** [comment]
that should be fixed in 16.2.27, could you double check the version you're using?

**Comment by yoleafbug** [comment]
Yes, you are right! So sorry, I mixed it up. I updated and all is well.

Btw, I've been taking your Tuto Official Rigging course and getting a ton
out of it-- thanks for the rad tools!
