### ISSUE TITLE
Dossier DuAEF qui apparait dans les documents Mac

### ISSUE THREAD

**Issue by gregmarcy** [Rainbox-dev/DuAEF_Duik#805]
**Describe the bug**
Un dossier DuAEF vide se créer à chaque lancement d'after effect, j'ai beau le supprimer, il revient à chaque fois.

**To Reproduce**
1. Suppression du dossier DuAEF dans les documents Mac
2. Lancement d'after effect
3. Le dossier réapparaît dans les documents

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**
<img width="780" alt="Capture d’écran 2021-01-31 à 12 47 54" src="https://user-images.githubusercontent.com/78302702/106382856-8b7d9300-63c2-11eb-9303-6331f55db142.png">

**System (please complete the following information):**
 - OS: 11.1
 - Version of After Effects: 17.6.0
 - Version of Duik: 16.2.27

**Additional context**

**Comment by Nico-Duduf** [comment]
correction dispo dans 16.2.28 demain
