### ISSUE TITLE
Dossier Duik Bassel.2 qui apparait dans les documents Mac

### ISSUE THREAD

**Issue by gregmarcy** [Rainbox-dev/DuAEF_Duik#806]
**Describe the bug**
Un dossier Duik Bassel.2 apparait dans les documents Mac, je le supprime, je lance after, je choisi mon dossier de réglage, je supprime le dossier Duik Bassel.2 de mes documents et au prochaine lancement d'After, le fichier Duik Bassel.2 réapparait dans mes documents Mac

**To Reproduce**
1. Supréssion du fichier Duik Bassel.2 
2. Lancement d'after effect
3. Choix du dossier de réglage vers un certain dossier
4. Réouverture d'after effect
5. Le fichier Duik Bassel.2 réapparait dans les documents Mac

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**
<img width="1071" alt="Capture d’écran 2021-01-31 à 12 56 31" src="https://user-images.githubusercontent.com/78302702/106383048-c59b6480-63c3-11eb-891d-75d434bad2c2.png">

**System (please complete the following information):**
 - OS: 11.1
 - Version of After Effects: 17.6.0
 - Version of Duik: 16.2.27

**Additional context**

**Comment by Nico-Duduf** [comment]
correction dispo dans 16.2.28 demain
