### ISSUE TITLE
Shot down

### ISSUE THREAD

**Issue by MKZ27** [Rainbox-dev/DuAEF_Duik#814]
Hi,
I want to do an IK rig with Duik but when I want to do that after effect CS6 shot down.
Help, please!

**Comment by Nico-Duduf** [comment]
We can't support CS6 anymore as Adobe has removed it from creative cloud. It's just too old.

That said, Duik should work, but as we can't test here, we need a lot more information to be able to know what's going on. Can you be more specific, and include the version of Duik too?
