### ISSUE TITLE
Spring button: multiple undo, error on no selected properties

### ISSUE THREAD

**Issue by Athari** [Rainbox-dev/DuAEF_Duik#819]
1. Clicking on Spring button results in multiple Undo steps being added (Kleaner and multiple Change Value).
2. When no properties are selected, this error message is displayed:

> **Script Alert**
> An error has occured in file
> /c/Program Files/Adobe/Adobe After Effects 2020/Support Files/Scripts/ScriptUI Panels/Duik Bassel.2.jsx
> at line 43986
> null is not an object
> **OK**

Code:

```js
/**
 * Spring
 */
Duik.automation.spring = function (  )
{
    var effects = Duik.animation.klean(false, false, true, true, false);
    if (effects.length == 0) return; // <<< 43986
    //deactivate the anticipation and the interpolation, and disable simulated mode
```

It would be nice if Duik displayed a meaningful warning that properties need to be selected first.

Windows 10 (19042.804), After Effects 2020 (17.7.0), Duik Bassel 2 (16.2.28)

**Comment by Nico-Duduf** [comment]
thanks for your feedback; both iussues are fixed in 16.2.29 available in a few days
