### ISSUE TITLE
Less of a bug and more of a complaint that your design is not idiot proof in the slightest

### ISSUE THREAD

**Issue by svirfneblins** [Rainbox-dev/DuAEF_Duik#820]
**Describe the bug**
What the heck is the zero button. Where do I find it. What does it look like? Can I use a zero button to retroactively find the zero position or is my rig completely fucked now and I have to start over? I can't find answers. But mostly, I can't find the goddamn button.

**To Reproduce**
1. Look at the manual that's been written for Duik and think about how a stupid person would approach looking for a button they have never seen before

**Expected behavior**

Check the manual > Read a concise description of what a button does, what it looks like, and where in the menus you will find it > Go back to After Effects and quickly find the button > Joy, Euphoria

>> vs what actually happens: check the manual > no images > not available in rookie mode? > check to see how to change from rookie to standard/expert settings > end up clicking around uselessly for five minutes until finding the settings tab for DUIK, not after effects > spend ten minutes writing a complaint about how hard it is to find ONE BUTTON > cry

**Screenshots**

I'd love to - unfortunately I don't know what I'm looking for!!

**System (please complete the following information):**
 - OS: Windows
 - Version of After Effects: newest
 - Version of Duik: also newest

**Additional context**

For gods sake think of the idiot students who are using your program.

**Comment by Kazryugo** [comment]
Hi, im having troble to find the zero button.

even putting on expert mode it doesent show up. Can, anybody help me?

System (please complete the following information):

OS: MAC
Version of After Effects: newest
Version of Duik: also newest
