### ISSUE TITLE
"extract" fails if rig comp has unicode characters in its name

### ISSUE THREAD

**Issue by gmatters** [Rainbox-dev/DuAEF_Duik#821]
**Describe the bug**

The unicode characters  a my rig comp are replaced by ??? in the expressions that Duik's "extract" feature creates.

I work with .ai files from a Japanese artist, and I haven't had any problems using basic rigging features such as zero layers, bones, controllers. But trying extract it got tripped up on the unicode characters.

**To Reproduce**
1.  I have a completed rig composition named "トラベラー 08"
2.  Embed it in an empty comp
3. Use DUIK 'extract' feature
4. Project contains 225 expression errors of the form var link = comp("????? 08").layer("LOC | master").transform.rotation;

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: macOS 10.12.6
 - Version of After Effects: CC 2017
 - Version of Duik: v16.2.28

**Additional context**

Renaming the rig comp before embedding it works around the problem

**Comment by Nico-Duduf** [comment]
Thanks for the feeback, I'll try to fix that ASAP, hoping it's something which can be fixed and not a limitation of expressions in Ae... I'll tell you in a few days!

**Comment by Nico-Duduf** [comment]
Hi,

I did not see you were still on CC2017; I believe this is a bug which has been fixed in recent versions of After Effects.

I've checked on my side with After Effects 2020, and it works correctly. Can you try that?
Thanks

**Comment by gmatters** [comment]
At the moment I only have an older laptop stuck on CC2017 so I can't test, feel free to close this and I can reopen if I hit it on a modern version. Thanks for looking into it.

**Comment by Nico-Duduf** [comment]
Noted, good luck then!
Thanks for your feedback
