### ISSUE TITLE
Fronzen After Effects

### ISSUE THREAD

**Issue by jhol17** [Rainbox-dev/DuAEF_Duik#825]
**Describe the bug**

**To Reproduce**
1. when a open After effects with duik script, it takes 30 seconds to open
2  when i open without duik it takes 4 seconds.
3 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

open after effects normal with frozen it.

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 17.0
 - Version of Duik: 16.2.28

**Additional context**

**Comment by Nico-Duduf** [comment]
Hi, I know this is an issue but unfortunately we can't do much about it. The Adobe scripting engine is just very slow at creating UI Panels. This will change in the future as Adobe is implementing a new engine, but for now  you'll just have to wait...
