### ISSUE TITLE
Plantage d'After Effects à l'ouverture et Bassel.2.jsx

### ISSUE THREAD

**Issue by MrPolo67** [Rainbox-dev/DuAEF_Duik#830]
**Describe the bug**
A l'ouverture d'After Effects 17.7.0, Extendscript Toolkit s'ouvre avec Bassel 2 et un plantage. voir PJ.

**To Reproduce**
1. Lancement d'AE
2. 
3. 

**Error description, if any**
File: Bassel.2.jsx
Line number: 35623
Error message: Erreur : XML error in line 194 section CDATA non fermée

**Expected behavior**
Rien. 

**Screenshots**
![Bug_2021_05_05_Plantage au demarrage de AE_17 7 0](https://user-images.githubusercontent.com/65020969/117191883-6180a600-ade1-11eb-80d0-9a825d4bb5f0.jpg)

**System (please complete the following information):**
 - OS: Win10 pro
 - Version of After Effects: 17.7.0
 - Version of Duik: v16.2.29

**Additional context**
Juste après démarrage de l'OS.

**Comment by Nico-Duduf** [comment]
Extendscript ne devrait pas s'ouvrir, c'est un bug de After Effects ça...

En désactivant le debogage javascript dans les preferences d'After Effects (section script et expressions), le problème sera réglé.
Le débogage ne devrait jamais être actif à moins qu'on soit en train de développer in script.
